const classMap = {
  1: "Beginner",
  2: "Journeyman",
  3: "Maestro",
  4: "Virtuoso",
  5: "Infinilyte",
  6: "Rage Basics",
  7: "Warrior",
  8: "Barbarian",
  9: "Squire",
  10: "Blood Berserker",
  11: "Death Bringer",
  12: "Divine Knight",
  13: "Royal Guardian",
  14: "Filler",
  15: "Filler",
  16: "Filler",
  17: "Filler",
  18: "Calm Basics",
  19: "Archer",
  20: "Bowman",
  21: "Hunter",
  22: "Siege Breaker",
  23: "Mayheim",
  24: "Wind Walker",
  25: "Beast Master",
  26: "Filler",
  27: "Filler",
  28: "Filler",
  29: "Filler",
  30: "Savvy Basics",
  31: "Mage",
  32: "Wizard",
  33: "Shaman",
  34: "Elemental Sorcerer",
  35: "Spiritual Monk",
  36: "Bubonic Conjuror",
  37: "Arcane Cultist",
  38: "Filler",
  39: "Filler",
  40: "Filler",
  41: "Filler",
};

const mapsMap = {
  0: "Blunder_Hills",
  1: "Spore_Meadows",
  2: "Froggy_Fields",
  3: "JungleZ",
  4: "PlayerSelect",
  5: "PlayerSelect",
  6: "Tunnels_Entrance",
  7: "Freefall_Caverns",
  8: "Poopy_Sewers",
  9: "The_Office",
  10: "The_Ol'_Straightaway",
  11: "Echoing_Egress",
  12: "Slip_Slidy_Ledges",
  13: "The_Base_Of_The_Bark",
  14: "Valley_Of_The_Beans",
  15: "Rats_Nest",
  16: "Jungle_Perimeter",
  17: "Birch_Enclave",
  18: "Hollowed_Trunk",
  19: "Winding_Willows",
  20: "TutorialA",
  21: "TutorialB",
  22: "TutorialC",
  23: "TutorialD",
  24: "Vegetable_Patch",
  25: "JungleX",
  26: "Forest_Outskirts",
  27: "Encroaching_Forest_Villas",
  28: "Tucked_Away",
  29: "End_Of_The_Road",
  30: "The_Roots",
  31: "Where_the_Branches_End",
  32: "MininggF",
  33: "How_Did_u_get_here",
  34: "Miningg1",
  35: "Miningg2",
  36: "Dewdrop_Colosseum",
  37: "Spike_Surprise",
  38: "Meel's_Crypt",
  39: "Grandfrog's_Backyard",
  40: "Z",
  41: "Z",
  42: "Z",
  43: "Z",
  44: "Z",
  45: "Z",
  46: "Z",
  47: "Z",
  48: "Z",
  49: "Z",
  50: "YumYum_Grotto",
  51: "Jar_Bridge",
  52: "The_Mimic_Hole",
  53: "Dessert_Dunes",
  54: "Salty_Shores",
  55: "Faraway_Piers",
  56: "Filler",
  57: "The_Grandioso_Canyon",
  58: "Shifty_Sandbox",
  59: "Pincer_Plateau",
  60: "Slamabam_Straightaway",
  61: "Deepwater_Docks",
  62: "The_Ring",
  63: "Up_Up_Down_Down",
  64: "Sands_of_Time",
  65: "Djonnuttown",
  66: "Efaunt's_Tomb",
  67: "Bandit_Bob's_Hideout",
  68: "Sandstone_Colosseum",
  69: "Mummy_Memorial",
  70: "Z",
  71: "Z",
  72: "Z",
  73: "Z",
  74: "Z",
  75: "Z",
  76: "Z",
  77: "Z",
  78: "Z",
  79: "Z",
  80: "Z",
  81: "Z",
  82: "Z",
  83: "Z",
  84: "Z",
  85: "Z",
  86: "Z",
  87: "Z",
  88: "Z",
  89: "Z",
  90: "Z",
  91: "Z",
  92: "Z",
  93: "Z",
  94: "Z",
  95: "Z",
  96: "Z",
  97: "Z",
  98: "Z",
  99: "Z",
  100: "Frostbite_Towndra",
  101: "Steep_Sheep_Ledge",
  102: "Trappers_Folley",
  103: "Snowfield_Outskirts",
  104: "The_Stache_Split",
  105: "Refrigeration_Station",
  106: "Mamooooth_Mountain",
  107: "Rollin'_Tundra",
  108: "Signature_Slopes",
  109: "Thermonuclear_Climb",
  110: "Waterlogged_Entrance",
  111: "Cryo_Catacombs",
  112: "Overpass_of_Sound",
  113: "Crystal_Basecamp",
  114: "Eycicles's_Nest",
  115: "Coldsnap_Colosseum",
  116: "Wam_Wonderland",
  117: "Hell_Hath_Frozen_Over",
  118: "filler",
  119: "filler",
};

// maps items stored names to their display name in game
const itemMap = {
  Blank: "None",
  LockedInvSpace: "LockedInvSpace",
  Trash: "Broken_Weapon",
  Copper: "Copper_Ore",
  Iron: "Iron_Ore",
  Gold: "Gold_Ore",
  Plat: "Platinum_Ore",
  Dementia: "Dementia_Ore",
  Void: "Void_Ore",
  Lustre: "Lustre_Ore",
  Starfire: "Starfire_Ore",
  Dreadlo: "Dreadlo_Ore",
  Godshard: "Godshard_Ore",
  CopperBar: "Copper_Bar",
  IronBar: "Iron_Bar",
  GoldBar: "Gold_Bar",
  PlatBar: "Platinum_Bar",
  DementiaBar: "Dementia_Bar",
  VoidBar: "Void_Bar",
  LustreBar: "Lustre_Bar",
  StarfireBar: "Starfire_Bar",
  DreadloBar: "Dreadlo_Bar",
  GodshardBar: "Godshard_Bar",
  OilBarrel1: "Crude_Oil",
  OilBarrel2: "Toxic_Sludge",
  OilBarrel3: "Radioactive_Waste",
  OilBarrel4: "Glumlee's_Special_Tutorial_Oil",
  OilBarrel5: "Eco_Friendly_Oil",
  OakTree: "Oak_Logs",
  BirchTree: "Bleach_Logs",
  JungleTree: "Jungle_Logs",
  ForestTree: "Forest_Fibres",
  ToiletTree: "Potty_Rolls",
  PalmTree: "Tropilogs",
  StumpTree: "Veiny_Logs",
  SaharanFoal: "Tundra_Logs",
  Tree7: "Wispy_Lumber",
  AlienTree: "Alien_Hive_Chunk",
  Leaf1: "Grass_Leaf",
  Leaf2: "Twisty_Leaf",
  Leaf3: "Arctic_Leaf",
  FillerMaterial: "Not_Yet",
  Fish1: "Goldfish",
  Fish2: "Hermit_Can",
  Fish3: "Jellyfish",
  Fish4: "Bloach",
  Fish5: "Filler",
  Fish6: "Filler",
  Fish7: "Filler",
  Fish8: "Filler",
  Bug1: "Fly",
  Bug2: "Butterfly",
  Bug3: "Sentient_Cereal",
  Bug4: "Fruitfly",
  Bug5: "Mosquisnow",
  Bug6: "Flycicle",
  Critter1: "Froge",
  Critter1A: "Poison_Froge",
  Critter2: "Crabbo",
  Critter2A: "Mutant_Crabbo",
  Critter3: "Scorpie",
  Critter3A: "Crescent_Scorpie",
  Critter4: "Mousey",
  Critter4A: "Nakeo_Moleo",
  Critter5: "Owlio",
  Critter5A: "Minervowl",
  Critter6: "Pingy",
  Critter6A: "Eternal_Lord_of_The_Undying_Ember",
  Critter7: "Bunny",
  Critter7A: "Purbunni",
  Critter8: "Dung_Beat",
  Critter8A: "Jade_Scarab",
  Critter9: "Honker",
  Critter9A: "Diamond_Duck",
  Soul1: "Forest_Soul",
  Soul2: "Dune_Soul",
  Soul3: "Rooted_Soul",
  Soul4: "Frigid_Soul",
  Soul5: "Squiddy_Soul",
  Soul6: "Cryo_Soul",
  EquipmentHats1: "Farmer_Brim",
  TestObj15: "Slime_Cap",
  EquipmentHatsBeg1: "Ice_Cream_Sunday",
  EquipmentHats61: "Mark_of_Member",
  EquipmentHats15: "Leather_Cap",
  EquipmentHats5: "White_Headband",
  EquipmentHats6: "Green_Headband",
  EquipmentHats7: "Red_Headband",
  EquipmentHats8: "Purple_Tupacband",
  EquipmentHats9: "Yellow_Headband",
  EquipmentHats10: "Pink_Headband",
  EquipmentHats11: "Grey_Beret",
  EquipmentHats12: "Traffic_Cone",
  EquipmentHats13: "Propeller_Cap",
  EquipmentHats14: "Baseball_Hat",
  TestObj14: "Trojan_Helmet",
  TestObj16: "Demon_Horns",
  EquipmentHats4Choppin: "Stump_Prop",
  EquipmentHats17: "Copper_Helmet",
  EquipmentHats18: "Iron_Helmet",
  EquipmentHats28: "Gold_Helmet",
  EquipmentHats22: "Amarok_Helmet",
  EquipmentHats19: "Platinum_Helmet",
  EquipmentHats53: "Dementia_Helmet",
  EquipmentHats52: "Efaunt_Helmet",
  EquipmentHats54: "Void_Imperium_Helmet",
  EquipmentHats21: "Party_Hat",
  EquipmentHats23: "Farmer_Brimer",
  EquipmentHats24: "Farmer_Brimest",
  EquipmentHats25: "Bored_Beanie",
  EquipmentHats2: "Royal_Turban",
  EquipmentHats27: "Paper_Boat",
  EquipmentHats29: "Alien_Headband",
  EquipmentHats30: "Cowbo_Galloneer",
  EquipmentHats39: "Grandma_Disguise",
  EquipmentHats42: "Santa_Hat",
  EquipmentHats44: "Jar",
  EquipmentHats51: "Big_Pretty_Bow",
  EquipmentHats55: "Steam_Cap",
  EquipmentHats56: "Bunny_Ears",
  EquipmentHats63: "Summer_Shell",
  EquipmentHats20: "Militia_Helm",
  TestObj13: "Viking_Cap",
  EquipmentHats58: "Murmillo_Helm",
  EquipmentHats3: "Thief_Hood",
  EquipmentHats41: "Sleek_Coif",
  EquipmentHats59: "Conquistador_Plume",
  EquipmentHats16: "Top_Hat",
  EquipmentHats26: "Witch_Hat",
  EquipmentHats60: "Adornment_of_the_High_Priest",
  EquipmentPunching1: "Boxing_Gloves",
  EquipmentPunching2: "The_Stingers",
  EquipmentPunching3: "Bandage_Wraps",
  EquipmentPunching4: "Uninflated_Glove",
  TestObj1: "Wooden_Spear",
  TestObj7: "Steel_Axe",
  TestObj3: "Royal_Bayonet",
  EquipmentSword1: "Enforced_Slasher",
  EquipmentSword2: "The_Ice_Breaker",
  EquipmentSword3: "Deuscythe",
  TestObj4: "Frozen_Impaler",
  TestObj5: "Blood_Screamer",
  TestObj8: "Flaming_Katana",
  TestObj9: "Emerald_Eizon",
  TestObj10: "Stalagmite",
  EquipmentWeapons1: "Iron_Sword",
  TestObj2: "Steel_Spear",
  EquipmentBows1: "Wooden_Bow",
  EquipmentBows3: "Birch_Longbow",
  EquipmentBows4: "Carrot_Launcher",
  EquipmentBows5: "Spiked_Menace",
  EquipmentBows6: "Pharoah_Bow",
  EquipmentBows7: "Blizzard_Bow",
  EquipmentBows8: "Blackhole_Bow",
  EquipmentWands1: "Gnarled_Wand",
  EquipmentWands2: "Quarterstaff",
  EquipmentWands5: "Starlight",
  EquipmentWands6: "Crows_Nest",
  EquipmentWands3: "Spriggly_Storm",
  EquipmentWands7: "Grey_Gatsby",
  EquipmentWands4: "Microphone",
  EquipmentShirts1: "Orange_Tee",
  EquipmentShirts2: "Blue_Tee",
  EquipmentShirts16: "Spore_Tee",
  EquipmentShirts3: "Black_Tee",
  EquipmentShirts4: "Tanned_Hide",
  EquipmentShirts6: "Paralax_Chest",
  EquipmentShirts7: "Molten_Chest",
  EquipmentShirts8: "REPLACE_ME",
  EquipmentShirts9: "REPLACE_ME",
  EquipmentShirts21: "Tattered_Cloth",
  EquipmentShirts10: "Fur_Shirt",
  EquipmentShirts11: "Copper_Platebody",
  EquipmentShirts12: "Iron_Platebody",
  EquipmentShirts13: "Gold_Platebody",
  EquipmentShirts18: "Amarok_Bodyplate",
  EquipmentShirts14: "Platinum_Platbody",
  EquipmentShirts15: "Dementia_Body",
  EquipmentShirts26: "Efaunt_Ribcage",
  EquipmentShirts27: "Void_Imperium_Platebody",
  EquipmentShirts17: "MCR_Tshirt",
  EquipmentShirts19: "Planktop",
  EquipmentShirts20: "Hide_Shirt",
  EquipmentShirts24: "Green_Tee",
  EquipmentShirts25: "Purple_Tee",
  EquipmentShirts31: "Member_Hoodie",
  EquipmentShirts5: "Studded_Hide",
  EquipmentShirts23: "Feral_Leathering",
  EquipmentShirts22: "Furled_Robes",
  EquipmentShirts28: "Damascus_Plates",
  EquipmentShirts29: "Evergreen_Wraps",
  EquipmentShirts30: "Elegantine_Robes",
  EquipmentPants1: "Torn_Jeans",
  EquipmentPants2: "Copper_Platelegs",
  EquipmentPants3: "Iron_Platelegs",
  EquipmentPants4: "Gold_Platelegs",
  EquipmentPants17: "Amarok_Hinds",
  EquipmentPants5: "Platinum_Shins",
  EquipmentPants6: "Dementia_Shins",
  EquipmentPants20: "Efaunt_Hipilium",
  EquipmentPants21: "Void_Imperium_Shardshins",
  EquipmentPants7: "Gilded_Pilates",
  EquipmentPants8: "Twisted_Scales",
  EquipmentPants9: "Crystallax_Shins",
  EquipmentPants10: "Give_Up_On_Life_Pants",
  EquipmentPants11: "Yellow_Belt_Ninja_Pants",
  EquipmentPants12: "Merchantile_Pants",
  EquipmentPants13: "Ancient_Leggings",
  EquipmentPants14: "Forensic_Leggings",
  EquipmentPants15: "Bleached_Designer_Wode_Patch_Pants",
  EquipmentPants16: "Adam's_Leaf",
  EquipmentPants18: "Dirty_Coal_Miner_Baggy_Soot_Pants",
  EquipmentPants19: "Trimmed_Rune_Platelegs",
  EquipmentPants22: "Fishing_Overalls",
  EquipmentPants23: "Bandito_Pantaloon",
  EquipmentShoes1: "Copper_Boots",
  EquipmentShoes15: "Iron_Boots",
  EquipmentShoes3: "Gold_Boots",
  EquipmentShoes20: "Amarok_Paws",
  EquipmentShoes4: "Platinum_Boots",
  EquipmentShoes5: "Dementia_Boots",
  EquipmentShoes21: "Efaunts_Broken_Ankles",
  EquipmentShoes22: "Void_Imperium_Kicks",
  EquipmentShoes6: "Hermes_Boots",
  EquipmentShoes7: "Goo_Galoshes",
  EquipmentShoes8: "Yeti_Walkers",
  EquipmentShoes9: "Flip_Flops",
  EquipmentShoes10: "Flap_Flops",
  EquipmentShoes11: "Floop_Flops",
  EquipmentShoes12: "Flux_Flops",
  EquipmentShoes13: "Gaia_Shoes",
  EquipmentShoes14: "Cauldrunners",
  EquipmentShoes16: "Cavern_Trekkers",
  EquipmentShoes17: "Logger_Heels",
  EquipmentShoes18: "Angler_Boots",
  EquipmentShoes19: "Bandito_Boots",
  EquipmentShoes2: "Eyern_Boots",
  EquipmentPendant1: "Mint_Icey",
  EquipmentPendant2: "Strawbu_Icey",
  EquipmentPendant3: "Rok_Road_Icey",
  EquipmentPendant4: "Rainbo_Icey",
  EquipmentPendant5: "Chocotastic_Icey",
  EquipmentPendant6: "Blubbery_Icey",
  EquipmentPendant7: "Lava_Icey",
  EquipmentPendant8: "Legends_Icey",
  EquipmentPendant9: "Little_Wooden_Katana",
  EquipmentPendant10: "Sleek_Shank",
  EquipmentPendant11: "Carrot_Horror",
  EquipmentPendant12: "Tarantulight",
  EquipmentPendant13: "Quartz_Pendant",
  EquipmentPendant14: "Fuscismatia",
  EquipmentPendant15: "Lucky_Fish_Head",
  EquipmentPendant16: "Strung_Bludgeon",
  EquipmentPendant17: "Chaotic_Amarok_Pendant",
  EquipmentPendant18: "Strung_Steamy",
  EquipmentRings1: "Gold_Ring",
  EquipmentRings2: "Copper_Band",
  EquipmentRings3: "Steel_Band",
  EquipmentRings4: "Molden_Crust",
  EquipmentRings5: "Toxic_Bubbles_Band",
  EquipmentRings6: "Death_Wish",
  EquipmentRings7: "Pugilist_Demise",
  EquipmentRings8: "The_Used_Bandaid",
  EquipmentRings9: "Chat_Ring",
  EquipmentRings10: "Spikeweed_Ring",
  EquipmentRings11: "Defenders_Dignity",
  EquipmentRingsFishing1: "Shallow_Watering",
  EquipmentRingsFishing2: "Oceanic_Ring",
  EquipmentRingsFishing3: "Deepwater_Trench_Ring",
  EquipmentRings12: "Frisbee_Ring",
  EquipmentRings13: "Silver_Stopwatch",
  EquipmentRings14: "Dooble_Goopi",
  EquipmentRings15: "Sanic_Ring",
  EquipmentRings16: "Efaunt_Trunculus",
  EquipmentRingsChat1: "Love_Ring",
  EquipmentRingsChat2: "Leafy_Ring",
  EquipmentRingsChat3: "Wealth_Ring",
  EquipmentRingsChat4: "Bob_Ring",
  EquipmentRingsChat5: "Bubble_Ring",
  EquipmentRingsChat6: "Cthulu's_Ring",
  EquipmentRingsChat8: "Lava_Sez_Buy_More_Gems",
  EquipmentRingsChat9: "HONK_Ring",
  EquipmentTools1: "Junk_Pickaxe",
  EquipmentTools2: "Copper_Pickaxe",
  EquipmentTools3: "Iron_Pickaxe",
  EquipmentTools5: "Gold_Pickaxe",
  EquipmentTools6: "Platinum_Pickaxe",
  EquipmentTools7: "Dementia_Pickaxe",
  EquipmentTools11: "Void_Imperium_Pik",
  EquipmentTools8: "Lustre_Pickaxe",
  EquipmentTools9: "Dreadlo_Pickolo",
  EquipmentTools10: "Poopy_Pickaxe",
  EquipmentToolsHatchet0: "Old_Hatchet",
  EquipmentToolsHatchet3: "Copper_Chopper",
  EquipmentToolsHatchet1: "Iron_Hatchet",
  EquipmentToolsHatchet2b: "Stinky_Axe",
  EquipmentToolsHatchet2: "Golden_Axe",
  EquipmentToolsHatchet4: "Plat_Hatchet",
  EquipmentToolsHatchet5: "Dementia_Dicer",
  EquipmentToolsHatchet7: "Void_Imperium_Axe",
  EquipmentToolsHatchet6: "Lustre_Logger",
  EquipmentToolsHatchet8: "Starfire_Hatchet",
  EquipmentToolsHatchet9: "Dreadlo_Eviscerator",
  EquipmentToolsHatchet10: "Annihilator_of_the_Yggdrasil",
  FishingRod1: "Wood_Fishing_Rod",
  FishingRod2: "Copper_Fish_Rod",
  FishingRod3: "Iron_Fishing_Rod",
  FishingRod4: "Gold_Fishing_Rod",
  FishingRod5: "Plat_Fishing_Rod",
  FishingRod6: "Dementia_Rod_for_Fishing",
  FishingRod7: "Void_Imperium_Rod",
  CatchingNet1: "Bug_Net",
  CatchingNet2: "Copper_Netted_Net",
  CatchingNet3: "Reinforced_Net",
  CatchingNet4: "Gilded_Net",
  CatchingNet5: "Platinet",
  CatchingNet6: "Dementia_Net",
  CatchingNet7: "Void_Imperium_Net",
  TrapBoxSet1: "Cardboard_Traps",
  TrapBoxSet2: "Silkskin_Traps",
  TrapBoxSet3: "Wooden_Traps",
  TrapBoxSet4: "Natural_Traps",
  TrapBoxSet5: "Steel_Traps",
  TrapBoxSet6: "Royal_Traps",
  WorshipSkull1: "Wax_Skull",
  WorshipSkull2: "Ceramic_Skull",
  WorshipSkull3: "Horned_Skull",
  WorshipSkull4: "Prickle_Skull",
  WorshipSkull5: "Manifested_Skull",
  WorshipSkull6: "Wax_Skull",
  FoodHealth1: "Nomwich",
  FoodHealth3: "Hot_Dog",
  FoodHealth2: "Cheezy_Pizza",
  Peanut: "Peanut",
  FoodHealth4: "Saucy_Weiner",
  FoodHealth6: "Kebab_Sticks",
  FoodHealth7: "Meat_Pie",
  FoodHealth10: "Mountain_Bread",
  FoodHealth9: "Yeti_Ham",
  FoodHealth11: "Sheepie_Dairy",
  FoodHealth5: "Cranberry_Jam",
  FoodHealth8: "Crabby_Cake_Supreme",
  FoodEvent8: "Milk_Choco",
  Meatloaf: "Magic_Meatloaf",
  FoodPotOr1: "Small_Strength_Potion",
  FoodPotOr2: "Average_Strength_Potion",
  FoodPotOr3: "Decent_Strength_Potion",
  FoodPotRe1: "Small_Life_Potion",
  FoodPotRe2: "Average_Life_Potion",
  FoodPotRe3: "Decent_Life_Potion",
  FoodPotGr1: "Small_Speed_Potion",
  FoodPotGr2: "Average_Speed_Potion",
  FoodPotGr3: "Decent_Speed_Potion",
  FoodEvent7: "Minto_Choco",
  FoodPotMana1: "Small_Mana_Potion",
  FoodPotMana2: "Average_Mana_Potion",
  FoodPotMana3: "Decent_Mana_Potion",
  FoodPotYe1: "Small_EXP_Potion",
  FoodPotYe2: "Average_EXP_Potion",
  FoodPotYe3: "Decent_EXP_Potion",
  FoodEvent6: "Lemony_Choco",
  Pearl3: "Shiny_Pearl",
  FoodMining1: "Icing_Ironbite",
  FoodEvent1: "Giftybread_Man",
  Pearl2: "Stained_Pearl",
  FoodChoppin1: "Saucy_Logfries",
  FoodEvent2: "Chogg_Nog",
  FoodFish1: "Slurpin_Herm",
  FoodEvent3: "Candy_Canes",
  Pearl1: "Aqua_Pearl",
  FoodCatch1: "Buttered_Toasted_Butter",
  FoodEvent4: "Mistleberries",
  FoodTrapping1: "Critter_Numnums",
  FoodWorship1: "Soulble_Gum",
  Bullet: "Bullet",
  BulletB: "FMJ_Bullet",
  MidnightCookie: "Midnight_Cookie",
  FoodEvent5: "Cherry_Choco",
  PeanutG: "Golden_Peanut",
  FoodG1: "Golden_Jam",
  FoodG2: "Golden_Kebabs",
  FoodG3: "Golden_Meat_Pie",
  FoodG4: "Golden_Nomwich",
  FoodG5: "Golden_Ham",
  FoodG6: "Golden_Bread",
  ButterBar: "Butter_Bar",
  rtt0: "Bottled_Town_Teleport",
  ResetFrag: "Talent_Point_Reset_Fragment",
  ResetCompleted: "Talent_Point_Reset_Potion",
  ResetCompletedS: "Star_Talent_Reset_Potion",
  ClassSwap: "Sub_Class_Swap_Token",
  ResetBox: "Post_Office_Box_Reseto_Magnifico",
  Ht: "Hat_Premiumifier",
  StonePremRestore: "Premium_Stone_Refunder",
  ExpBalloon1: "Small_Experience_Balloon",
  ExpBalloon2: "Medium_Experience_Balloon",
  ExpBalloon3: "Large_Experience_Balloon",
  JobApplication: "Job_Application",
  SmithingHammerChisel: "Sculpting_Tools",
  BobJoePickle: "BobJoePickle",
  Quest1: "Mining_Certificate",
  Crystal1: "Desert_Topaz",
  Crystal2: "Glacier_Quartz",
  Crystal3: "Galaxial_Amethyst",
  Quest2: "Mining_Certificate",
  PeanutS: "Stone_Peanut",
  Quest3: "Ketchup_Bottle",
  Quest4: "Mustard_Bottle",
  Quest5: "Golden_Jam",
  Quest6: "Scouting_Report",
  Quest7: "Strange_Rock",
  Quest8: "Filler_bc_I_messed_up",
  Quest10: "Green_Tea",
  Quest11: "Forest_Villas_Flyer_Thingy",
  Quest12: "Dog_Bone",
  Quest13: "Empty_Box",
  Quest14: "Employment_Statistics",
  Quest15: "Red_Frisbee",
  Quest16: "Broken_Mic",
  Quest17: "Amarok_Slab",
  Quest18: "Loomi's_Room_Key",
  Quest19: "Golden_Dubloon",
  Quest20: "Signed_Arrest_Warrant",
  Quest21: "Time_Thingy",
  Quest22: "Corporatube_Sub",
  Quest23: "Instablab_Follower",
  Quest24: "Cloudsound_Follower",
  Quest25: "Birthday_Card",
  Quest26: "Pre_Crime_Box",
  Quest27: "Bag_o_Nuts",
  Quest28: "IOU_One_Blue_Crystal",
  Quest29: "Chaotic_Amarok_Slab",
  GoldricP1: "Casual_Confidante",
  GoldricP2: "Triumphant_Treason",
  GoldricP3: "Claiming_Cashe",
  Quest30: "Giftmas_Box",
  Quest31: "Gem_Note",
  Cutter: "Bolt_Cutters",
  Quest32: "Monster_Rating",
  Quest33: "Player_Rating_With_Letter_P",
  Quest34: "Player_Rating_With_Letter_S",
  Quest35: "Googley_Eyes",
  Quest36: "Dootjat_Eye",
  Quest37: "Silver_Antique",
  Quest38: "Guild_Giftbox",
  Quest39: "Lovey_Dovey_Letter",
  Quest40: "Choco_Box",
  Quest41: "Flowies",
  Quest42: "Egg_Capsule",
  Quest43: "Gummy_Bunny",
  Quest44: "Goldegg_Capsule",
  Quest45: "Sesame_Seed",
  Quest46: "The_Bobber_Challenge_Scroll",
  Quest47: "Elderly_Peanut",
  Quest48: "Pete_the_Peanut",
  Quest49: "Summer_Cooler",
  Quest50: "Beach_Oyster",
  Pearl4: "Black_Pearl",
  Quest9: "Picnic_Token",
  BadgeG1: "Blunderhills_NPC_Completion_Token",
  BadgeG2: "Blunder_Skills_Completion_Token",
  BadgeG3: "Blunderhills_Misc_Completion_Token",
  BadgeD1: "Yumyum_Desert_NPC_Completion_Token",
  BadgeD2: "Yumyum_Skills_Completion_Token",
  BadgeD3: "Yumyum_Misc_Completion_Token",
  NPCtoken1: "Easy_Blunderhills_NPC_Token",
  NPCtoken2: "Med_Blunderhills_NPC_Token",
  NPCtoken3: "Hard_Blunderhills_NPC_Token",
  NPCtoken4: "Stiltzcho_Token",
  NPCtoken5: "Woodsman_Token",
  NPCtoken6: "Glumlee_Token",
  NPCtoken7: "Papua_Piggea_Token",
  NPCtoken8: "FILLER",
  NPCtoken9: "Funguy_Token",
  NPCtoken10: "Krunk_Token",
  NPCtoken11: "Tiki_Chief_Token",
  NPCtoken12: "Sproutinald_Token",
  NPCtoken13: "Dog_Bone_Token",
  NPCtoken14: "Dazey_Token",
  NPCtoken15: "TP_Pete_Token",
  NPCtoken16: "Bandit_Bob_Token",
  NPCtoken17: "Snake_Jar_Token",
  NPCtoken18: "Whattso_Token",
  NPCtoken19: "Cowbo_Jones_Token",
  NPCtoken20: "Carpetiem_Token",
  NPCtoken21: "Goldric_Token",
  NPCtoken27: "Cattleprod_Token",
  NPCtoken22: "Fishpaste_Token",
  NPCtoken24: "Loominadi_Token",
  NPCtoken25: "Djonnut_Token",
  NPCtoken26: "Scubidew_Token",
  NPCtoken23: "Wellington_Token",
  NPCtoken28: "Easy_Yumyum_Dez_NPC_Token",
  NPCtoken29: "Med_Yumyum_Dez_NPC_Token",
  NPCtoken30: "Hard_Yumyum_Dez_NPC_Token",
  EquipmentSmithingTabs2: "Anvil_Tab_2",
  EquipmentSmithingTabs3: "Anvil_Tab_3",
  EquipmentSmithingTabs4: "Anvil_Tab_4",
  EquipmentSmithingTabs5: "Anvil_Tab_5",
  EquipmentSmithingTabs6: "Anvil_Tab_6",
  EquipmentSmithingTabs7: "Anvil_Tab_7",
  EquipmentSmithingTabs8: "Anvil_Tab_8",
  EquipmentStatues1: "Power_Statue",
  EquipmentStatues2: "Speed_Statue",
  EquipmentStatues3: "Mining_Statue",
  EquipmentStatues4: "Feasty_Statue",
  EquipmentStatues5: "Health_Statue",
  EquipmentStatues6: "Kachow_Statue",
  EquipmentStatues7: "Lumberbob_Statue",
  EquipmentStatues8: "Thicc_Skin_Statue",
  EquipmentStatues9: "Oceanman_Statue",
  EquipmentStatues10: "Ol_Reliable_Statue",
  EquipmentStatues11: "Exp_Book_Statue",
  EquipmentStatues12: "Anvil_Statue",
  EquipmentStatues13: "Cauldron_Statue",
  EquipmentStatues14: "Beholder_Statue",
  EquipmentStatues15: "Bullseye_Statue",
  EquipmentStatues16: "Box_Statue",
  EquipmentStatues17: "Twosoul_Statue",
  EquipmentStatues18: "EhExPee_Statue",
  EquipmentStatues19: "Seesaw_Statue",
  SmithingRecipes1: "Beginner_Recipe",
  SmithingRecipes2: "Novice_Recipe",
  SmithingRecipes3: "Apprentice_Recipe",
  SmithingRecipes4: "Journeyman_Recipe",
  TalentBook1: "Special_Talent_Book",
  TalentBook2: "Beginner_Talent_Book",
  TalentBook3: "Warrior_Talent_Book",
  TalentBook4: "Archer_Talent_Book",
  TalentBook5: "Wizard_Talent_Book",
  MaxCapBagT2: "Miniature_Mining_Pouch",
  MaxCapBag1: "Cramped_Mining_Pouch",
  MaxCapBag2: "Small_Mining_Pouch",
  MaxCapBag3: "Average_Mining_Pouch",
  MaxCapBag4: "Sizable_Mining_Pouch",
  MaxCapBag5: "Big_Mining_Pouch",
  MaxCapBagMi6: "Large_Mining_Pouch",
  MaxCapBagT1: "Miniature_Choppin_Pouch",
  MaxCapBag7: "Cramped_Choppin_Pouch",
  MaxCapBag9: "Small_Choppin_Pouch",
  MaxCapBagT3: "Average_Choppin_Pouch",
  MaxCapBagT4: "Sizable_Choppin_Pouch",
  MaxCapBagT5: "Big_Choppin_Pouch",
  MaxCapBagT6: "Large_Choppin_Pouch",
  MaxCapBag6: "Miniscule_Food_Pouch",
  MaxCapBag8: "Cramped_Food_Pouch",
  MaxCapBag10: "Small_Food_Pouch",
  MaxCapBagF3: "Average_Food_Pouch",
  MaxCapBagF4: "Sizable_Food_Pouch",
  MaxCapBagF5: "Big_Food_Pouch",
  MaxCapBagF6: "Large_Food_Pouch",
  MaxCapBagM1: "Mini_Materials_Pouch",
  MaxCapBagM2: "Cramped_Material_Pouch",
  MaxCapBagM3: "Small_Material_Pouch",
  MaxCapBagM4: "Average_Material_Pouch",
  MaxCapBagM5: "Sizable_Materials_Pouch",
  MaxCapBagM6: "Big_Materials_Pouch",
  MaxCapBagM7: "Large_Materials_Pouch",
  MaxCapBagFi0: "Miniature_Fish_Pouch",
  MaxCapBagFi1: "Cramped_Fish_Pouch",
  MaxCapBagFi2: "Small_Fish_Pouch",
  MaxCapBagFi3: "Average_Fish_Pouch",
  MaxCapBagFi4: "Sizable_Fish_Pouch",
  MaxCapBagFi5: "Big_Fish_Pouch",
  MaxCapBagFi6: "Large_Fish_Pouch",
  MaxCapBagB0: "Miniature_Bug_Pouch",
  MaxCapBagB1: "Cramped_Bug_Pouch",
  MaxCapBagB2: "Small_Bug_Pouch",
  MaxCapBagB3: "Average_Bug_Pouch",
  MaxCapBagB4: "Sizable_Bug_Pouch",
  MaxCapBagB5: "Big_Bug_Pouch",
  MaxCapBagB6: "Large_Bug_Pouch",
  MaxCapBagTr0: "Cramped_Critter_Pouch",
  MaxCapBagTr1: "Small_Critter_Pouch",
  MaxCapBagTr2: "Average_Critter_Pouch",
  MaxCapBagTr3: "Sizable_Critter_Pouch",
  MaxCapBagTr4: "Big_Critter_Pouch",
  MaxCapBagTr5: "Large_Critter_Pouch",
  MaxCapBagS0: "Cramped_Soul_Pouch",
  MaxCapBagS1: "Small_Soul_Pouch",
  MaxCapBagS2: "Average_Soul_Pouch",
  MaxCapBagS3: "Sizable_Soul_Pouch",
  MaxCapBagS4: "Big_Soul_Pouch",
  MaxCapBagS5: "Large_Soul_Pouch",
  ObolBronze0: "Bronze_STR_Obol",
  ObolBronze1: "Bronze_AGI_Obol",
  ObolBronze2: "Bronze_WIS_Obol",
  ObolBronze3: "Bronze_LUK_Obol",
  ObolSilver0: "Silver_STR_Obol",
  ObolSilver1: "Silver_AGI_Obol",
  ObolSilver2: "Silver_WIS_Obol",
  ObolSilver3: "Silver_LUK_Obol",
  ObolGold0: "Gold_STR_Obol",
  ObolGold1: "Gold_AGI_Obol",
  ObolGold2: "Gold_WIS_Obol",
  ObolGold3: "Gold_LUK_Obol",
  ObolPlatinum0: "Platinum_STR_Obol",
  ObolPlatinum1: "Platinum_AGI_Obol",
  ObolPlatinum2: "Platinum_WIS_Obol",
  ObolPlatinum3: "Platinum_LUK_Obol",
  ObolPink0: "Dementia_STR_Obol",
  ObolPink1: "Dementia_AGI_Obol",
  ObolPink2: "Dementia_WIS_Obol",
  ObolPink3: "Dementia_LUK_Obol",
  ObolBronzeDamage: "Bronze_Obol_of_Puny_Damage",
  ObolSilverDamage: "Silver_Obol_of_Little_Damage",
  ObolGoldDamage: "Golden_Obol_of_Big_Boy_Damage",
  ObolPlatinumDamage: "Platinum_Obol_of_Lethal_Damage",
  ObolPinkDamage: "Dementia_Obol_of_Infinite_Damage",
  ObolPlatinumSpeed: "Platinum_Obol_of_Blinding_Speed",
  ObolSilverMoney: "Silver_Obol_of_Pocket_Change",
  ObolGoldMoney: "Golden_Obol_of_Plentiful_Riches",
  ObolBronzeMining: "Bronze_Obol_of_Small_Swings",
  ObolSilverMining: "Silver_Obol_of_Moderate_Mining",
  ObolGoldMining: "Golden_Obol_of_Diligent_Digging",
  ObolPlatinumMining: "Platinum_Obol_of_Dwarven_Delving",
  ObolPinkMining: "Dementia_Obol_of_Magisterial_Metals",
  ObolBronzeChoppin: "Bronze_Obol_of_Chippin_Chops",
  ObolSilverChoppin: "Silver_Obol_of_Big_Bark",
  ObolGoldChoppin: "Golden_Obol_of_Huge_Hackin",
  ObolPlatinumChoppin: "Platinum_Obol_of_Lumby_Loggo",
  ObolPinkChoppin: "Dementia_Obol_of_WOWOWOWWO",
  ObolBronzeFishing: "Bronze_Obol_of_Finite_Fish",
  ObolSilverFishing: "Silver_Obol_of_Puny_Pikes",
  ObolGoldFishing: "Golden_Obol_of_Crazy_Carp",
  ObolPlatinumFishing: "Platinum_Obol_of_Tremendous_Trout",
  ObolPinkFishing: "Dementia_Obol_of_Monument_Marlins",
  ObolBronzeCatching: "Bronze_Obol_of_Few_Flies",
  ObolSilverCatching: "Silver_Obol_of_Big_Bugs",
  ObolGoldCatching: "Golden_Obol_of_Insane_Insects",
  ObolPlatinumCatching: "Platinum_Obol_of_Idk_Yet",
  ObolPinkCatching: "Dementia_Obol_of_Idk_Yet",
  ObolSilverLuck: "Silver_Obol_of_Double_Sixes",
  ObolGoldLuck: "Golden_Obol_of_Triple_Sixes",
  ObolPlatinumLuck: "Platinum_Obol_of_Yahtzee_Sixes",
  ObolPinkLuck: "Dementia_Obol_of_Infinisixes",
  ObolBronzePop: "Bronze_Obol_of_Pop",
  ObolSilverPop: "Silver_Obol_of_Pop_Pop",
  ObolGoldPop: "Golden_Obol_of_Poppity_Pop",
  ObolPlatinumPop: "Platinum_Obol_of_Poppity_Poppy",
  ObolPinkPop: "Dementia_Obol_of_Pop_Pop_Pop_Pop",
  ObolEfauntA: "Skeletal_Obol_of_Efaunt's_Gaze",
  ObolAmarokA: "Granite_Obol_of_Amarok's_Stare",
  ObolBronzeKill: "Bronze_Obol_of_Multikill",
  ObolSilverKill: "Silver_Obol_of_Megakill",
  ObolGoldKill: "Golden_Obol_of_Ultrakill",
  ObolPlatinumKill: "Platinum_Obol_of_Killimanjaro",
  ObolPinkKill: "Dementia_Obol_of_Killionaire",
  ObolBronzeEXP: "Bronze_Obol_of_Experience",
  ObolSilverEXP: "Silver_Obol_of_Experience",
  ObolGoldEXP: "Golden_Obol_of_Experience",
  ObolPlatinumEXP: "Platinum_Obol_of_Experience",
  ObolPinkEXP: "Dementia_Obol_of_Experience",
  ObolBronzeCard: "Bronze_Obol_of_Cards",
  ObolSilverCard: "Silver_Obol_of_Cards",
  ObolGoldCard: "Golden_Obol_of_Cards",
  ObolPlatinumCard: "Platinum_Obol_of_Cards",
  ObolPinkCard: "Dementia_Obol_of_Cards",
  ObolBronzeDef: "Bronze_Obol_of_Defence",
  ObolSilverDef: "Silver_Obol_of_Defence",
  ObolGoldDef: "Golden_Obol_of_Defence",
  ObolPlatinumDef: "Platinum_Obol_of_Defense_with_an_S",
  ObolPinkDef: "Dementia_Obol_of_Defence",
  ObolBronzeTrapping: "Bronze_Obol_of_Trapping",
  ObolSilverTrapping: "Silver_Obol_of_Trapping",
  ObolGoldTrapping: "Golden_Obol_of_Trapping",
  ObolPlatinumTrapping: "Platinum_Obol_of_Trapping",
  ObolPinkTrapping: "Dementia_Obol_of_Trapping",
  ObolBronzeCons: "Bronze_Obol_of_Construction",
  ObolSilverCons: "Silver_Obol_of_Construction",
  ObolGoldCons: "Golden_Obol_of_Construction",
  ObolPlatinumCons: "Platinum_Obol_of_Construction",
  ObolPinkCons: "Dementia_Obol_of_Construction",
  ObolBronzeWorship: "Bronze_Obol_of_Worship",
  ObolSilverWorship: "Silver_Obol_of_Worship",
  ObolGoldWorship: "Golden_Obol_of_Worship",
  ObolPlatinumWorship: "Platinum_Obol_of_Worship",
  ObolPinkWorship: "Dementia_Obol_of_Worship",
  ExpSmith1: "Smithing_Exp",
  StampA1: "Sword_Stamp",
  StampA2: "Heart_Stamp",
  StampA3: "Mana_Stamp",
  StampA4: "Tomahawk_Stamp",
  StampA5: "Target_Stamp",
  StampA6: "Shield_Stamp",
  StampA7: "Longsword_Stamp",
  StampA8: "Kapow_Stamp",
  StampA9: "Fist_Stamp",
  StampA10: "Battleaxe_Stamp",
  StampA11: "Agile_Stamp",
  StampA12: "Vitality_Stamp",
  StampA13: "Book_Stamp",
  StampA14: "Manamoar_Stamp",
  StampA15: "Clover_Stamp",
  StampA16: "Scimitar_Stamp",
  StampA17: "Bullseye_Stamp",
  StampA18: "Feather_Stamp",
  StampA19: "Polearm_Stamp",
  StampA20: "Violence_Stamp",
  StampA21: "Buckler_Stamp",
  StampA22: "FILLER",
  StampA23: "Sukka_Foo",
  StampA24: "Arcane_Stamp",
  StampA25: "FILLER",
  StampA26: "Steve_Sword",
  StampA27: "Blover_Stamp",
  StampA28: "Stat_Graph_Stamp",
  StampA29: "FILLER",
  StampA30: "FILLER",
  StampA31: "FILLER",
  StampA32: "FILLER",
  StampA33: "FILLER",
  StampA34: "FILLER",
  StampA35: "FILLER",
  StampB1: "Pickaxe_Stamp",
  StampB2: "Hatchet_Stamp",
  StampB3: "Anvil_Zoomer_Stamp",
  StampB4: "Lil' Mining_Baggy_Stamp",
  StampB5: "Twin_Ores_Stamp",
  StampB6: "Choppin' Bag_Stamp",
  StampB7: "Duplogs_Stamp",
  StampB8: "Matty_Bag_Stamp",
  StampB9: "Smart_Dirt_Stamp",
  StampB10: "Cool_Diggy_Tool_Stamp",
  StampB11: "High_IQ_Lumber_Stamp",
  StampB12: "Swag_Swingy_Tool_Stamp",
  StampB13: "Alch_Go_Brrr_Stamp",
  StampB14: "Brainstew_Stamps",
  StampB15: "Drippy_Drop_Stamp",
  StampB16: "Droplots_Stamp",
  StampB17: "Fishing_Rod_Stamp",
  StampB18: "Fishhead_Stamp",
  StampB19: "Catch_Net_Stamp",
  StampB20: "Fly_Intel_Stamp",
  StampB21: "Bag_o_Heads_Stamp",
  StampB22: "Holy_Mackerel_Stamp",
  StampB23: "Bugsack_Stamp",
  StampB24: "Buzz_Buzz_Stamp",
  StampB25: "Hidey_Box_Stamp",
  StampB26: "Purp_Froge_Stamp",
  StampB27: "Spikemouth_Stamp",
  StampB28: "Shiny_Crab_Stamp",
  StampB29: "Gear_Stamp",
  StampB30: "Sample_Stamp",
  StampB31: "Saw_Stamp",
  StampB32: "Amplesample_Stamp",
  StampB33: "SpoOoky_Stamp",
  StampB34: "Flowin_Stamp",
  StampB35: "Prayday_Stamp",
  StampB36: "Banked_Pts_Stamp",
  StampC1: "Questin_Stamp",
  StampC2: "Mason_Jar_Stamp",
  StampC3: "Crystallin",
  StampC4: "Blank",
  StampC5: "Apple_Stamp",
  StampC6: "Potion_Stamp",
  StampC7: "Golden_Apple_Stamp",
  StampC8: "Blank",
  StampC9: "Card_Stamp",
  StampC10: "Blank",
  StampC11: "Blank",
  StampC12: "Blank",
  StampC13: "Talent_I_Stamp",
  StampC14: "Talent_II_Stamp",
  StampC15: "Talent_III_Stamp",
  StampC16: "Talent_IV_Stamp",
  StampC17: "Talent_V_Stamp",
  StampC18: "Talent_S_Stamp",
  StampC19: "Multikill_Stamp",
  StampC20: "Biblio_Stamp",
  StoneWe: "Easter_Weapon_Stone",
  StoneWeb: "Summer_Weapon_Stone",
  StoneW1: "Weapon_Upgrade_Stone_I",
  StoneW2: "Weapon_Upgrade_Stone_II",
  StoneW3: "Weapon_Upgrade_Stone_III",
  StoneW6: "Warped_Weapon_Upgrade_Stone",
  StoneAe: "Easter_Armor_Stone",
  StoneAeB: "Summer_Armor_Stone",
  StoneA1: "Armor_Upgrade_Stone_I",
  StoneA1b: "Armor_Upgrade_Stone_G",
  StoneA2: "Armor_Upgrade_Stone_II",
  StoneA2b: "Armor_Upgrade_Stone_B",
  StoneA3: "Armor_Upgrade_Stone_III",
  StoneA3b: "Armor_Upgrade_Stone_C",
  StoneTe: "Easter_Tool_Upgrade_Stone",
  StoneT1: "Tool_Upgrade_Stone_I",
  StoneT1e: "Giftmas_Tool_Upgrade_Stone",
  StoneT1eb: "Summer_Tool_Upgrade_Stone",
  StoneT2: "Tool_Upgrade_Stone_II",
  StoneT3: "Tool_Upgrade_Stone_III",
  StoneHelm1: "Helmet_Upgrade_Stone_I",
  StoneHelm6: "Warped_Helmet_Upgrade_Stone",
  StoneHelm1b: "Giftmas_Helmet_Upgrade_Stone",
  StoneZ1: "Mystery_Upgrade_Stone_I",
  StoneZ2: "Mystery_Upgrade_Stone_II",
  StonePremSTR: "Premium_STR_Stone",
  StonePremAGI: "Premium_AGI_Stone",
  StonePremWIS: "Premium_WIS_Stone",
  StonePremLUK: "Premium_LUK_Stone",
  Refinery1: "Redox_Salts",
  Refinery2: "Explosive_Salts",
  Refinery3: "Spontaneity_Salts",
  Refinery4: "Dioxide_Synthesis",
  Refinery5: "Red_Salt",
  Refinery6: "Red_Salt_2",
  "CraftMat1": "Thread",
  "CraftMat2": "Crimson_String",
  "CraftMat3": "Cue_Tape",
  "CraftMat5": "Trusty_Nails",
  "CraftMat6": "Boring_Brick",
  "CraftMat7": "Chain_Link",
  "CraftMat9": "Leather_Hide",
  "CraftMat8": "Pinion_Spur",
  "CraftMat10": "Lugi_Bracket",
  CraftMat11: "Filler",
  CraftMat12: "Filler",
  CraftMat13: "Filler",
  CraftMat14: "Filler",
  CraftMat15: "Filler",
  CraftMat16: "Filler",
  CraftMat17: "Filler",
  PureWater: "Distilled_Water",
  PureWater2: "Dense_Water",
  Grasslands1: "Spore_Cap",
  Grasslands2: "Frog_Leg",
  Grasslands3: "Bean_Slices",
  Grasslands4: "Red_Spore_Cap",
  Jungle1: "Slime_Sludge",
  Jungle2: "Snake_Skin",
  Jungle3: "Carrot_Cube",
  Forest1: "Goblin_Ear",
  Forest2: "Plank",
  Forest3: "Bullfrog_Horn",
  Sewers1: "Corn_Kernels",
  Sewers1b: "Golden_Plop",
  Sewers2: "Rats_Tail",
  Sewers3: "Bonemeal",
  TreeInterior1: "Stick",
  TreeInterior1b: "Woodular_Circle",
  TreeInterior2: "Acorn",
  BabaYagaETC: "Baba_Yaga_Baby_Eggs",
  DesertA1: "Pocket_Sand",
  DesertA1b: "Glass_Shard",
  DesertA2: "Megalodon_Tooth",
  DesertA3: "Crabby_Cakey",
  DesertA3b: "Nuget_Cake",
  DesertB1: "Coconotnotto",
  DesertB2: "Furled_Flag",
  DesertB3: "Pincer_Arm",
  DesertB4: "Potato_Remains",
  DesertC1: "High_Steaks",
  DesertC2: "Wakka_Cherry",
  DesertC2b: "Ghost",
  DesertC3: "Singlecle",
  DesertC4: "Shrapshell",
  SnowA1: "Floof_Ploof",
  SnowA2: "Melty_Cube",
  SnowA2a: "Yellow_Snowflake",
  SnowA3: "Moustache_Comb",
  SnowA4: "Ram_Wool",
  SnowB1: "Sticky_Stick",
  SnowB2: "Mamooth_Tusk",
  SnowB2a: "Ice_Age_3",
  SnowB5: "Snow_Ball",
  SnowB3: "Pen",
  SnowB4: "Cracked_Glass",
  SnowC1: "Sippy_Straw",
  SnowC2: "Cryosnake_Skin",
  SnowC3: "Audio_Cord",
  SnowC4: "Contact_Lense",
  SnowC4a: "Black_Lense",
  IceMountains2: "Ice_A_La_Crem",
  Hgg: "Minuteglass",
  EfauntDrop1: "Ripped_Tunic",
  EfauntDrop2: "Ribbed_Tunic",
  Trophy1: "King_of_Food",
  Trophy2: "Lucky_Lad",
  Trophy3: "Club_Member",
  Trophy4: "I_Made_This_Game",
  Trophy5: "Dice_Dynamo",
  Trophy6: "Blunder_Hero",
  Trophy7: "Original_Gamer",
  Trophy8: "Trailblazer",
  Trophy9: "Ultra_Unboxer",
  Trophy10: "Critter_Baron",
  Trophy11: "YumYum_Sheriff",
  Trophy12: "Megalodon",
  Trophy13: "Club_Maestro",
  Trophy14: "Beach_Bro",
  Starlight: "Starlight_Ore",
  AlienTreetutorial: "Alien_Logs",
  EquipmentWeapons2: "Flesh_Reaper",
  Secretstone: "Secretstone",
  Timecandy1: "1_HR_Time_Candy",
  Timecandy2: "2_HR_Time_Candy",
  Timecandy3: "4_HR_Time_Candy",
  Timecandy4: "12_HR_Time_Candy",
  Timecandy5: "24_HR_Time_Candy",
  Timecandy6: "72_HR_Time_Candy",
  Timecandy7: "Steamy_Time_Candy",
  InvBag1: "Inventory_Bag_A",
  InvBag2: "Inventory_Bag_B",
  InvBag3: "Inventory_Bag_C",
  InvBag4: "Inventory_Bag_D",
  InvBag5: "Inventory_Bag_E",
  InvBag6: "Inventory_Bag_F",
  InvBag7: "Inventory_Bag_G",
  InvBag8: "Inventory_Bag_H",
  InvBag9: "Inventory_Bag_I",
  InvBag21: "Inventory_Bag_U",
  InvBag22: "Inventory_Bag_V",
  InvBag23: "Inventory_Bag_W",
  InvBag24: "Inventory_Bag_X",
  InvBag25: "Inventory_Bag_Y",
  InvBag26: "Inventory_Bag_Z",
  InvBag100: "Snakeskinventory_Bag",
  InvBag101: "Totally_Normal_and_not_fake_Bag",
  InvBag102: "Blunderbag",
  InvBag103: "Sandy_Satchel",
  InvBag104: "Bummo_Bag",
  InvBag105: "Capitalist_Case",
  InvBag106: "Wealthy_Wallet",
  InvBag107: "Prosperous_Pouch",
  InvBag108: "Sack_of_Success",
  InvBag109: "Shivering_Sack",
  InvBag110: "Mamooth_Hide_Bag",
  InvStorage1: "Storage_Chest_1",
  InvStorage2: "Storage_Chest_2",
  InvStorage3: "Storage_Chest_3",
  InvStorage4: "Storage_Chest_4",
  InvStorage5: "Storage_Chest_5",
  InvStorage6: "Storage_Chest_6",
  InvStorage7: "Storage_Chest_7",
  InvStorage8: "Storage_Chest_8",
  InvStorage9: "Storage_Chest_9",
  InvStorage10: "Storage_Chest_10",
  InvStorage11: "Storage_Chest_11",
  InvStorage12: "Storage_Chest_12",
  InvStorage13: "Storage_Chest_13",
  InvStorage14: "Storage_Chest_14",
  InvStorage15: "Storage_Chest_15",
  InvStorage16: "Storage_Chest_16",
  InvStorage17: "Storage_Chest_17",
  InvStorage18: "Storage_Chest_18",
  InvStorage19: "Storage_Chest_19",
  InvStorage20: "Storage_Chest_20",
  InvStorage21: "Storage_Chest_21",
  InvStorage31: "Storage_Chest_90",
  InvStorage32: "Storage_Chest_91",
  InvStorage33: "Storage_Chest_92",
  InvStorage34: "Storage_Chest_93",
  InvStorage35: "Storage_Chest_94",
  InvStorage36: "Storage_Chest_95",
  InvStorage37: "Storage_Chest_96",
  InvStorage38: "Storage_Chest_97",
  InvStorage39: "Storage_Chest_98",
  InvStorage40: "Storage_Chest_99",
  InvStorage41: "Storage_Chest_99B",
  InvStorage42: "Storage_Chest_99C",
  InvStorageF: "Dank_Paypay_Chest",
  Key1: "Forest_Villa_Key",
  Key2: "Efaunt's_Tomb_Key",
  Key3: "Chizoar's_Cavern_Key",
  ObolFrag: "Obol_Fragment",
  DoubleAFKtix: "Double_AFK_Gain_Ticket",
  TixCol: "Colosseum_Ticket",
  DeliveryBox: "Delivery_Box",
  SilverPen: "Silver_Pen",
  PremiumGem: "Gem",
  TalentPoint1: "Talent_Point_Tab_1",
  TalentPoint2: "Talent_Point_Tab_2",
  TalentPoint3: "Talent_Point_Tab_3",
  TalentPoint4: "Talent_Point_Tab_4",
  TalentPoint5: "Talent_Point_Tab_5",
  TalentPoint6: "Talent_Point_Special_Tab",
  Line1: "Copper_Twine",
  Line2: "Silver_Twine",
  Line3: "Gold_Twine",
  Line4: "Platinum_Twine",
  Line5: "Leafy_Vines",
  Line6: "Fun_Flags",
  Line7: "Electrical_Wiring",
  Line8: "Wiener_Links",
  Line9: "Zeus_Gon_Fishin",
  Line10: "Needledrop",
  Line11: "Spoons_Lol",
  Line12: "Its_a_Boy_Celebration",
  Line13: "Its_a_Girl_Celebration",
  Line14: "Its_Alright_Celebration",
  Weight1: "Wormie_Weight",
  Weight2: "Iron_Hook",
  Weight3: "Basic_Bobber",
  Weight4: "Dualhook_Prongs",
  Weight5: "One_Pound_of_Steel",
  Weight6: "One_Pound_of_Feathers",
  Weight7: "Massless_Unit_for_Physics_Questions",
  Weight8: "Literal_Elephant",
  Weight9: "Valve_Patented_Circle_Thingies",
  Weight10: "Dynamite",
  Weight11: "Not_Dynamite",
  Weight12: "Triple_Threat",
  Weight13: "Crash_Box",
  Weight14: "Fat_Albert",
  CardPack1: "Newbie_Card_Pack",
  CardPack2: "Ancient_Card_Pack",
  CardPack3: "Eternal_Card_Pack",
  EquipmentHats31: "Smitty's_Bubble_Blowing_Hat",
  EquipmentHats32: "Bandit_Bob_Mask",
  EquipmentHats33: "Paper_Bag",
  EquipmentHats34: "Parasite",
  EquipmentHats35: "Diamon_Horns",
  EquipmentHats36: "Halloween_Pumpkin",
  EquipmentHats40: "Pardoned_Turkey",
  EquipmentHats37: "Hotdog_Hero",
  EquipmentHats38: "Invisible_Hat",
  EquipmentHats46: "Strawbiggy",
  EquipmentHats47: "Pop_Cat",
  EquipmentHats48: "Dairy_Dunk",
  EquipmentHats49: "The_Classic",
  EquipmentHats50: "Green_Beanie",
  EquipmentHats43: "Snowman",
  EquipmentHats45: "Giftmas_Tree",
  EquipmentHats57: "Big_Bunny",
  EquipmentHats62: "Fluffy_Ramsy",
  GemP1: "Infinite_Forge",
  GemP9: "Quality_Obol_Stack",
  GemP10: "Marvelous_Obol_Stack",
  GemQ1: "Infinite_Forge",
  GemQ2: "Infinite_Forge",
  GemQ3: "Infinite_Forge",
  GemQ4: "Infinite_Forge",
  GemQ5: "Infinite_Forge",
  GemQ6: "Infinite_Forge",
  GemQ7: "Infinite_Forge",
  GemQ8: "Infinite_Forge",
  Mayo: "Maynaise_Bottle",
  CardsA0: "Green_Mushroom_Card",
  CardsA1: "Red_Mushroom_Card",
  CardsA2: "Frog_Card",
  CardsA3: "Bored_Bean_Card",
  CardsA4: "Slime_Card",
  CardsA5: "Baby_Boa_Card",
  CardsA6: "Carrotman_Card",
  CardsA7: "Glublin_Card",
  CardsA8: "Wode_Board_Card",
  CardsA9: "Gigafrog_Card",
  CardsA10: "Poop_Card",
  CardsA11: "Rat_Card",
  CardsA12: "Walking_Stick_Card",
  CardsA13: "Nutto_Card",
  CardsA14: "Crystal_Carrot_Card",
  CardsA15: "Poop_Card",
  CardsA16: "Wood_Mushroom_Card",
  CardsB1: "Sandy_Pot_Card",
  CardsB2: "Mimic_Card",
  CardsB3: "Crabcake_Card",
  CardsB4: "Mafioso_Card",
  CardsB5: "Sand_Castle_Card",
  CardsB6: "Pincermin_Card",
  CardsB7: "Mashed_Potato_Card",
  CardsB8: "Tyson_Card",
  CardsB9: "Moonmoon_Card",
  CardsB10: "Sand_Giant_Card",
  CardsB11: "Snelbie_Card",
  CardsB12: "Dig_Doug_Card",
  CardsB13: "Crystal_Crabal_Card",
  CardsB14: "Bandit_Bob_Card",
  CardsC1: "Copper_Ore_Card",
  CardsC2: "Iron_Ore_Card",
  CardsC3: "Gold_Ore_Card",
  CardsC4: "Oak_Tree_Card",
  CardsC5: "Bleach_Logs_Card",
  CardsC6: "Jungle_Logs_Card",
  CardsC7: "Forest_Fibres_Card",
  CardsC8: "Goldfish_Card",
  CardsC9: "Hermit_Can_Card",
  CardsC10: "Jellyfish_Card",
  CardsC11: "Fly_Card",
  CardsC12: "Butterfly_Card",
  CardsC13: "",
  CardsC14: "",
  CardsC15: "",
  CardsC16: "Fire_Forge_Card",
  CardsD1: "Dementia_Ore_Card",
  CardsD2: "Platinum_Ore_Card",
  CardsD3: "Void_Ore_Card",
  CardsD4: "Lustre_Ore_Card",
  CardsD5: "Potty_Rolls_Card",
  CardsD6: "Veiny_Logs_Card",
  CardsD7: "Tropilogs_Card",
  CardsD8: "Tundra_Logs_Card",
  CardsD9: "Fruitfly_Card",
  CardsD10: "Sentient_Cereal_Card",
  CardsD11: "Fly_Card",
  CardsD12: "",
  CardsD13: "",
  CardsD16: "Cinder_Forge_Card",
  CardsD17: "Forest_Soul_Card",
  CardsD18: "Dune_Soul_Card",
  CardsD19: "Froge_Card",
  CardsD20: "Crabbo_Card",
  CardsD21: "Scorpie_Card",
  CardsE0: "Frost_Flake_Card",
  CardsE1: "Sheepie_Card",
  CardsE2: "Sir_Stache_Card",
  CardsE3: "Bloque_Card",
  CardsE4: "Mamooth_Card",
  CardsE5: "Snowman_Card",
  CardsE6: "Penguin_Card",
  CardsE7: "Thermister_Card",
  CardsE8: "Quenchie_Card",
  CardsE9: "Cryosnake_Card",
  CardsE10: "Bop_Box_Card",
  CardsE11: "Neyeptune_Card",
  CardsE12: "Xylobone_Card",
  CardsE13: "Bloodbone_Card",
  CardsE14: "Dedotated_Ram_Card",
  CardsE15: "Crystal_Cattle_Card",
  CardsF1: "",
  CardsF2: "Wispy_Lumber_Card",
  CardsF3: "Rooted_Soul_Card",
  CardsF4: "Mousey_Card",
  CardsF5: "Owlio_Card",
  CardsF6: "Pingy_Card",
  CardsF7: "Bunny_Card",
  CardsF8: "Mosquisnow_Card",
  CardsF9: "Flycicle_Card",
  CardsF10: "Frigid_Soul_Card",
  CardsF11: "Squiddy_Soul_Card",
  CardsY0: "Ghost_Card",
  CardsY1: "Giftmas_Blobulyte_Card",
  CardsY2: "Meaning_of_Giftmas_Card",
  CardsY3: "Valentslime_Card",
  CardsY4: "Loveulyte_Card",
  CardsY5: "Chocco_Box_Card",
  CardsY6: "Floofie_Card",
  CardsY7: "Shell_Snake_Card",
  CardsY8: "Egggulyte_Card",
  CardsY9: "Egg_Capsule_Card",
  CardsY10: "Mr_Blueberry_Card",
  CardsY11: "Coastiolyte_Card",
  CardsY12: "Summer_Spirit_Card",
  CardsY13: "Plasti_Doug_Card",
  CardsZ0: "Baba_Yaga_Card",
  CardsZ1: "Dr_Defecaus_Card",
  CardsZ2: "Amarok_Card",
  CardsZ3: "Chaotic_Amarok_Card",
  CardsZ4: "Biggie_Hours_Card",
  CardsZ5: "King_Doot_Card",
  CardsZ6: "Efaunt_Card",
  CardsZ7: "Chaotic_Efaunt_Card",
  CardsZ8: "Chizoar_Card",
  CardsZ9: "Chaotic_Chizoar_Card"
};

const bubblesMap = {
  _11: "Call_Me_Bob",
  _6: "Sploosh_Sploosh",
  _3: "Wyoming_Blood",
  a11: "Call_Me_Ash",
  a7: "Sanic_Tools",
  a2: "Hammer_Hammer",
  b11: "Call_Me_Pope",
  b7: "Cookin_Roadkill",
  b3: "Molto_Loggo",
  c12: "Big_Game_Hunter",
  c8: "Grind_Time",
  c3: "Level_Up_Gift",
};

const starSignMap = {
  0: {
    name: "The_Buff_Guy",
    description: "+1%_Total_Damage +3_STR",
  },
  1: {
    name: "Flexo_Bendo",
    description: "+2%_Movement_Speed +3_AGI",
  },
  2: {
    name: "The_Book_Worm",
    description: "+1%_Class_EXP_Gain +3_WIS",
  },
  3: {
    name: "The_Fuzzy_Dice",
    description: "+3_Talent_Points +3_LUK",
  },
  4: {
    name: "Dwarfo_Beardus",
    description: "+5%_Mining_Efficency +20%_Multi-Ore_Chance",
  },
  5: {
    name: "Hipster_Logger",
    description: "+5%_Chop_Efficiency +20%_Multi-Log_Chance",
  },
  6: {
    name: "Pie_Seas",
    description: "+5%_Fishin_Efficency +20%_Multi-Fish_Odds",
  },
  7: {
    name: "Shoe_Fly",
    description: "+5%_Catch_Efficiency +20%_Multi-Bug_Chance",
  },
  8: {
    name: "Blue_Hedgehog",
    description: "+4%_Movement_Speed +0.0001%_Ring_Drop",
  },
  9: {
    name: "Gum_Drop",
    description: "+15%_to_get_a_Time Candy_when_claiming 8+_Hour_AFK_gains",
  },
  10: {
    name: "Activelius",
    description: "+15%_Class_EXP_when fighting_actively",
  },
  11: {
    name: "Pack_Mule",
    description: "+10%_Carry_Cap",
  },
  12: {
    name: "Ned_Kelly",
    description: "+6%_Defence +2_Weapon_Power",
  },
  13: {
    name: "Robinhood",
    description: "+4%_Accuracy +2%_Movement_Speed +1_Cant_Trade_GME",
  },
  14: {
    name: "Pirate_Booty",
    description: "+5%_Drop_Rate",
  },
  15: {
    name: "Muscle_Man",
    description: "+8_STR",
  },
  16: {
    name: "Fast_Frog",
    description: "+8_AGI",
  },
  17: {
    name: "Smart_Stooge",
    description: "+8_WIS",
  },
  18: {
    name: "Lucky_Larry",
    description: "+8_LUK",
  },
  19: {
    name: "Silly_Snoozer",
    description: "+2%_Fight_AFK_Gain",
  },
  20: {
    name: "The_Big_Comatose",
    description: "+2%_Skill_AFK_Gain",
  },
  21: {
    name: "Miniature_Game",
    description: "+30%_minigame_reward",
  },
  22: {
    name: "Mount_Eaterest",
    description: "+10%_chance_to_not consume_food +15%_All_Food_Effect",
  },
  23: {
    name: "Bob_Build_Guy",
    description: "+10%_Speed_in_Town Skills",
  },
  24: {
    name: "The_Big_Brain",
    description: "+3%_Class_EXP_gain",
  },
  25: {
    name: "The_OG_Skiller",
    description: "+5%_Carry_Cap +1%_Skill_AFK_gain +2%_All_Skill_Prowess",
  },
  26: {
    name: "Grim_Reaper",
    description: "+2%_Mob_Respawn_rate",
  },
  27: {
    name: "The_Fallen_Titan",
    description: "+3%_Boss_Damage +4%_Crit_Chance",
  },
  28: {
    name: "The_Forsaken",
    description: "-80%_Total_HP -50%_Defence +6%_Fight_AFK_Gain",
  },
  29: {
    name: "Mr_No_Sleep",
    description: "-6%_AFK_Gain +30%_Carry_Cap",
  },
  30: {
    name: "Sir_Savvy",
    description: "+3%_Skill_EXP_gain",
  },
  31: {
    name: "All_Rounder",
    description: "+4_All_Stats",
  },
  32: {
    name: "Fatty_Doodoo",
    description: "-3%_Movement_Speed +5%_Defence +2%_Total_Damage",
  },
  33: {
    name: "Chronus_Cosmos",
    description: "All_characters_can now_align_with_2 Star_Signs_at_once",
  },
};

const cardSetMap = {
  None: "None",
  "{%_EXP_if_below_Lv_50": { name: "Blunder_Hills", rawName: 'CardSet0', base: 8 },
  "{%_All_Food_Effect": { name: "Yum-Yum_Desert", rawName: 'CardSet1', base: 10 },
  "{%_Skill_Efficiency": { name: "Easy_Resources", rawName: 'CardSet2', base: 8 },
  "{%_Skill_EXP_Gain": { name: "Medium_Resources", rawName: 'CardSet3', base: 5 },
  "{%_DEF_and_ACC": { name: "Frostbite_Tundra", rawName: 'CardSet4', base: 5 },
  "{%_Skill_AFK_Gain_Rate": { name: "Hard_Resources", rawName: 'CardSet5', base: 4 },
  "{%_Dmg,_Drop,_and_EXP": { name: "Bosses_n_Nightmares", rawName: 'CardSet26', base: 6 },
  "{%_Drop_Rate": { name: "Events", rawName: 'CardSet25', base: 5 },
};

const cardEquipMap = {
  B: "None",
  mushG: "Green Mushroom (+ Base HP)",
  mushR: "Red Mushroom (+ Base LUK)",
  frogG: "Frog (+ Base MP)",
  beanG: "Bored Bean (+ Base Damage)",
  slimeG: "Slime (+ Base WIS)",
  snakeG: "Baby Boa (+ Move Spd)",
  carrotO: "Carrotman (+ Base AGI)",
  goblinG: "Glublin (+% Total HP)",
  plank: "Wode Board (+ Base STR)",
  frogBIG: "Gigafrog (+% Card Drop Chance)",
  poopSmall: "Poop (+% Crystal Mob Spawn Chance)",
  ratB: "Rat (+% Critical Chance)",
  branch: "Walking Stick (+ Base WIS)",
  acorn: "Nutto (+% Money from Monsters)",
  Crystal0: "Crystal Carrot (+% Total Drop Rate)",
  mushW: "Wood Mushroom (+% Total Accuracy)",
  jarSand: "Sandy Pot (+% EXP Conversion from Talent)",
  mimicA: "Mimic (+% Total Drop Rate)",
  crabcake: "Crabcake (+% To not consume Food)",
  coconut: "Mafioso (+ Base AGI)",
  sandcastle: "Sand Castle (+% Total Accuracy)",
  pincermin: "Pincermin (+ Weapon Power)",
  potato: "Mashed Potato (+% Critical Damage)",
  steak: "Tyson (+ Base STR)",
  moonman: "Moonmoon (+% Monster EXP While Active)",
  sandgiant: "Sand Giant (+% Minimum Damage)",
  snailZ: "Snelbie (+% Card Drop Chance)",
  shovelR: "Dig Doug (+ Base LUK)",
  Crystal1: "Crystal Crabal (+% EXP from monsters)",
  Bandit_Bob: "Bandit Bob (+% Money from Monsters)",
  Copper: "Copper Ore (+ Base accuracy)",
  Iron: "Iron Ore (+% Total Mining Efficiency)",
  Gold: "Gold Ore (+% Mining EXP)",
  ForgeA: "Fire Forge (+% Smithing EXP)",
  OakTree: "Oak Tree (+ Base Defence)",
  BirchTree: "Bleach Logs (+% Total Choppin Efficiency)",
  JungleTree: "Jungle Logs (+% Choppin EXP)",
  ForestTree: "Forest Fibres (+% EXP Conversion from Talent)",
  Fish1: "Goldfish (+% Total MP)",
  Fish2: "Hermit Can (+% Total Fishing Efficiency)",
  Fish3: "Jellyfish (+% Fishing EXP)",
  Bug1: "Fly (+% Monster EXP While Active)",
  Bug2: "Butterfly (+% Total Catching Efficiency)",
  Plat: "Platinum Ore (+% Mining Away Gains)",
  Dementia: "Dementia Ore (+% Mining Speed)",
  Void: "Void Ore (+% Card Drop Chance)",
  ForgeB: "Cinder Forge (+% Smithing EXP)",
  PalmTree: "Tropilogs (+% Choppin Away Gains)",
  ToiletTree: "Potty Rolls (+% Choppin Speed)",
  StumpTree: "Veiny Logs (+% Total Accuracy)",
  Fish4: "Bloach (+% Fishing Away Gains)",
  Bug3: "Sentient Cereal (+% Catching EXP)",
  Bug4: "Fruitfly (+% Catching Away Gains)",
  SoulCard1: "Forest Soul (+% Defence from Equipment)",
  SoulCard2: "Dune Soul (+% Max Charge)",
  CritterCard1: "Froge (+% Shiny Critter Chance)",
  CritterCard2: "Crabbo (+% Trapping Efficiency)",
  CritterCard3: "Scorpie (+% Trapping EXP)",
  sheep: "Sheepie (+% Defence from Equipment)",
  flake: "Frost Flake (+ Base STR)",
  stache: "Sir Stache (+% Card Drop Chance)",
  bloque: "Bloque (+ Base AGI)",
  mamoth: "Mamooth (+% Total HP)",
  snowball: "Snowman (+% Total Damage)",
  penguin: "Penguin (+ Base WIS)",
  thermostat: "Thermister (+% Critical Damage)",
  glass: "Quenchie (+ Base LUK)",
  snakeB: "Cryosnake (+% MP regen rate)",
  speaker: "Bop Box (+% Total Drop Rate)",
  eye: "Neyeptune (+% Total Accuracy)",
  ram: "Dedotated Ram (+ Weapon Power)",
  skele: "Xylobone (+% Critical Chance)",
  skele2: "Bloodbone (+% Total Damage)",
  Crystal2: "Crystal Cattle (+% EXP from monsters)",
  Tree7: "Wispy Lumber (+% Choppin Speed)",
  SoulCard3: "Rooted Soul (+ Starting Pts in Worship)",
  SoulCard4: "Frigid Soul (+% Max Charge)",
  SoulCard5: "Squiddy Soul (+% Charge Rate)",
  CritterCard4: "Mousey (+% Shiny Critter Chance)",
  CritterCard5: "Owlio (+% EXP from monsters)",
  CritterCard6: "Pingy (+% Shiny Critter Chance)",
  CritterCard7: "Bunny (+% Skill AFK gain rate)",
  Lustre: "Lustre Ore (+ Base LUK)",
  SaharanFoal: "Tundra Logs (+% Choppin Away Gains)",
  Bug5: "Mosquisnow (+% Total Catching Efficiency)",
  Bug6: "Flycicle (+% Catching Away Gains)",
  babayaga: "Baba Yaga (+% Money from Monsters)",
  poopBig: "Dr Defecaus (+% Total Damage)",
  poopD: "Boop (+% Fighting AFK gain rate)",
  wolfA: "Amarok (+% Skill AFK gain rate)",
  wolfB: "Chaotic Amarok (+% Fighting AFK gain rate)",
  babaHour: "Biggie Hours (+% Double AFK claim chance)",
  babaMummy: "King Doot (+% Total Drop Rate)",
  Boss2A: "Efaunt (+% EXP from monsters)",
  Boss2B: "Chaotic Efaunt (+% Skill EXP)",
  Boss3A: "Chizoar (+% Cog Build Spd (Passive))",
  Boss3B: "Chaotic Chizoar (+% Shrine Effects)",
  ghost: "Ghost (+% Monster EXP While Active)",
  xmasEvent: "Giftmas Blobulyte (+% Total Drop Rate)",
  xmasEvent2: "Meaning of Giftmas (+% Money from Monsters)",
  slimeR: "Valentslime (+% Defence from Equipment)",
  loveEvent: "Loveulyte (+% Total HP)",
  loveEvent2: "Chocco Box (+% Boost Food Effect)",
  sheepB: "Floofie (+% MP regen rate)",
  snakeY: "Shell Snake (+ Base LUK)",
  EasterEvent1: "Egggulyte (+% Card Drop Chance)",
  EasterEvent2: "Egg Capsule (+% Critical Damage)",
  SummerEvent1: "Coastiolyte (+% Fishing Away Gains)",
  SummerEvent2: "Summer Spirit (+% Catching EXP)",
  shovelY: "Plasti Doug (+ Base Defence)",
  crabcakeB: "Mr Blueberry (+% Total Drop Rate)",
};

const cardLevelMap = {
  mushG: 5,
  mushR: 10,
  frogG: 6,
  beanG: 7,
  slimeG: 8,
  snakeG: 9,
  carrotO: 10,
  goblinG: 10,
  plank: 10,
  frogBIG: 10,
  poopSmall: 10,
  ratB: 10,
  branch: 10,
  acorn: 10,
  Crystal0: 3,
  mushW: 10,
  jarSand: 10,
  mimicA: 10,
  crabcake: 10,
  coconut: 10,
  sandcastle: 10,
  pincermin: 10,
  potato: 10,
  steak: 10,
  moonman: 10,
  sandgiant: 10,
  snailZ: 10,
  shovelR: 10,
  Crystal1: 3,
  Bandit_Bob: 1,
  Copper: 10,
  Iron: 10,
  Gold: 10,
  ForgeA: 10,
  OakTree: 10,
  BirchTree: 10,
  JungleTree: 10,
  ForestTree: 10,
  Fish1: 10,
  Fish2: 10,
  Fish3: 10,
  Bug1: 10,
  Bug2: 10,
  Plat: 10,
  Dementia: 10,
  Void: 10,
  ForgeB: 10,
  PalmTree: 10,
  ToiletTree: 10,
  StumpTree: 10,
  Fish4: 10,
  Bug3: 10,
  Bug4: 10,
  SoulCard1: 3,
  SoulCard2: 3,
  CritterCard1: 4,
  CritterCard2: 4,
  CritterCard3: 4,
  sheep: 11,
  flake: 12,
  stache: 13,
  bloque: 14,
  mamoth: 15,
  snowball: 15,
  penguin: 15,
  thermostat: 15,
  glass: 17,
  snakeB: 17,
  speaker: 17,
  eye: 17,
  ram: 20,
  skele: 15,
  skele2: 15,
  Crystal2: 10,
  Tree7: 10,
  SoulCard3: 3,
  SoulCard4: 4,
  SoulCard5: 5,
  CritterCard4: 4,
  CritterCard5: 4,
  CritterCard6: 5,
  CritterCard7: 6,
  Lustre: 10,
  SaharanFoal: 10,
  Bug5: 10,
  Bug6: 10,
  babayaga: 1.5,
  poopBig: 1.5,
  poopD: 1,
  wolfA: 1.5,
  wolfB: 1.5,
  babaHour: 1.5,
  babaMummy: 1.5,
  Boss2A: 1.5,
  Boss2B: 1.5,
  Boss3A: 1.5,
  Boss3B: 1.5,
  ghost: 2,
  xmasEvent: 1.5,
  xmasEvent2: 1.5,
  slimeR: 2,
  loveEvent: 1.5,
  loveEvent2: 1.5,
  sheepB: 3,
  snakeY: 3,
  EasterEvent1: 1.5,
  EasterEvent2: 1.5,

  Blank: 0,
};

const skillIndexMap = {
  0: "character",
  1: "mining",
  2: "smithing",
  3: "chopping",
  4: "fishing",
  5: "alchemy",
  6: "catching",
  7: "trapping",
  8: "construction",
  9: "worship",
};

const anvilProductionItems = {
  0: "Thread",
  1: "Trusty_Nails",
  2: "Boring_Brick",
  3: "Chain_Link",
  4: "Leather_Hide",
  5: "Pinion_Spur",
  6: "Lugi_Bracket"
}

const guildBonusesMap = {
  0: "Guild_Gifts",
  1: "Stat_Runes",
  2: "Rucksack",
  3: "Power_of_Pow",
  4: "REM_Fighting",
  5: "Make_or_Break",
  6: "Multi_Tool",
  7: "Sleepy_Skiller",
  8: "Wait_A_Minute",
  9: "Bonus_GP_for_small_guilds",
  10: "Gold_Charm",
  11: "Star_Dazzle",
  12: "C2_Card_Spotter",
  13: "Bestone",
  14: "Wait_A_Minute",
  15: "Craps",
  16: "Anotha_One",
  17: "Wait_A_Minute",
};

const obolMap = {
  "ObolLocked1": "Locked",
  "ObolLocked2": "Locked",
  "ObolLocked3": "Locked",
  "ObolLocked4": "Locked",
  "Blank": "Empty",
  "ObolAmarokA": "Granite_Obol_of_Amarok's_Stare",
  "ObolBronze0": "Bronze_STR_Obol",
  "ObolBronze1": "Bronze_AGI_Obol",
  "ObolBronze2": "Bronze_WIS_Obol",
  "ObolBronze3": "Bronze_LUK_Obol",
  "ObolBronzeCard": "Bronze_Obol_of_Cards",
  "ObolBronzeCatching": "Bronze_Obol_of_Few_Flies",
  "ObolBronzeChoppin": "Bronze_Obol_of_Chippin_Chops",
  "ObolBronzeCons": "Bronze_Obol_of_Construction",
  "ObolBronzeDamage": "Bronze_Obol_of_Puny_Damage",
  "ObolBronzeDef": "Bronze_Obol_of_Defence",
  "ObolBronzeEXP": "Bronze_Obol_of_Experience",
  "ObolBronzeFishing": "Bronze_Obol_of_Finite_Fish",
  "ObolBronzeKill": "Bronze_Obol_of_Multikill",
  "ObolBronzeMining": "Bronze_Obol_of_Small_Swings",
  "ObolBronzePop": "Bronze_Obol_of_Pop",
  "ObolBronzeTrapping": "Bronze_Obol_of_Trapping",
  "ObolBronzeWorship": "Bronze_Obol_of_Worship",
  "ObolEfauntA": "Skeletal_Obol_of_Efaunt's_Gaze",
  "ObolGold0": "Gold_STR_Obol",
  "ObolGold1": "Gold_AGI_Obol",
  "ObolGold2": "Gold_WIS_Obol",
  "ObolGold3": "Gold_LUK_Obol",
  "ObolGoldCard": "Golden_Obol_of_Cards",
  "ObolGoldCatching": "Golden_Obol_of_Insane_Insects",
  "ObolGoldChoppin": "Golden_Obol_of_Huge_Hackin",
  "ObolGoldCons": "Golden_Obol_of_Construction",
  "ObolGoldDamage": "Golden_Obol_of_Big_Boy_Damage",
  "ObolGoldDef": "Golden_Obol_of_Defence",
  "ObolGoldEXP": "Golden_Obol_of_Experience",
  "ObolGoldFishing": "Golden_Obol_of_Crazy_Carp",
  "ObolGoldKill": "Golden_Obol_of_Ultrakill",
  "ObolGoldLuck": "Golden_Obol_of_Triple_Sixes",
  "ObolGoldMining": "Golden_Obol_of_Diligent_Digging",
  "ObolGoldMoney": "Golden_Obol_of_Plentiful_Riches",
  "ObolGoldPop": "Golden_Obol_of_Poppity_Pop",
  "ObolGoldTrapping": "Golden_Obol_of_Trapping",
  "ObolGoldWorship": "Golden_Obol_of_Worship",
  "ObolPink0": "Dementia_STR_Obol",
  "ObolPink1": "Dementia_AGI_Obol",
  "ObolPink2": "Dementia_WIS_Obol",
  "ObolPink3": "Dementia_LUK_Obol",
  "ObolPinkCard": "Dementia_Obol_of_Cards",
  "ObolPinkCatching": "Dementia_Obol_of_Idk_Yet",
  "ObolPinkChoppin": "Dementia_Obol_of_WOWOWOWWO",
  "ObolPinkCons": "Dementia_Obol_of_Construction",
  "ObolPinkDamage": "Dementia_Obol_of_Infinite_Damage",
  "ObolPinkDef": "Dementia_Obol_of_Defence",
  "ObolPinkEXP": "Dementia_Obol_of_Experience",
  "ObolPinkFishing": "Dementia_Obol_of_Monument_Marlins",
  "ObolPinkKill": "Dementia_Obol_of_Killionaire",
  "ObolPinkLuck": "Dementia_Obol_of_Infinisixes",
  "ObolPinkMining": "Dementia_Obol_of_Magisterial_Metals",
  "ObolPinkPop": "Dementia_Obol_of_Pop_Pop_Pop_Pop",
  "ObolPinkTrapping": "Dementia_Obol_of_Trapping",
  "ObolPinkWorship": "Dementia_Obol_of_Worship",
  "ObolPlatinum0": "Platinum_STR_Obol",
  "ObolPlatinum1": "Platinum_AGI_Obol",
  "ObolPlatinum2": "Platinum_WIS_Obol",
  "ObolPlatinum3": "Platinum_LUK_Obol",
  "ObolPlatinumCard": "Platinum_Obol_of_Cards",
  "ObolPlatinumCatching": "Platinum_Obol_of_Idk_Yet",
  "ObolPlatinumChoppin": "Platinum_Obol_of_Lumby_Loggo",
  "ObolPlatinumCons": "Platinum_Obol_of_Construction",
  "ObolPlatinumDamage": "Platinum_Obol_of_Lethal_Damage",
  "ObolPlatinumDef": "Platinum_Obol_of_Defense_with_an_S",
  "ObolPlatinumEXP": "Platinum_Obol_of_Experience",
  "ObolPlatinumFishing": "Platinum_Obol_of_Tremendous_Trout",
  "ObolPlatinumKill": "Platinum_Obol_of_Killimanjaro",
  "ObolPlatinumLuck": "Platinum_Obol_of_Yahtzee_Sixes",
  "ObolPlatinumMining": "Platinum_Obol_of_Dwarven_Delving",
  "ObolPlatinumPop": "Platinum_Obol_of_Poppity_Poppy",
  "ObolPlatinumSpeed": "Platinum_Obol_of_Blinding_Speed",
  "ObolPlatinumTrapping": "Platinum_Obol_of_Trapping",
  "ObolPlatinumWorship": "Platinum_Obol_of_Worship",
  "ObolSilver0": "Silver_STR_Obol",
  "ObolSilver1": "Silver_AGI_Obol",
  "ObolSilver2": "Silver_WIS_Obol",
  "ObolSilver3": "Silver_LUK_Obol",
  "ObolSilverCard": "Silver_Obol_of_Cards",
  "ObolSilverCatching": "Silver_Obol_of_Big_Bugs",
  "ObolSilverChoppin": "Silver_Obol_of_Big_Bark",
  "ObolSilverCons": "Silver_Obol_of_Construction",
  "ObolSilverDamage": "Silver_Obol_of_Little_Damage",
  "ObolSilverDef": "Silver_Obol_of_Defence",
  "ObolSilverEXP": "Silver_Obol_of_Experience",
  "ObolSilverFishing": "Silver_Obol_of_Puny_Pikes",
  "ObolSilverKill": "Silver_Obol_of_Megakill",
  "ObolSilverLuck": "Silver_Obol_of_Double_Sixes",
  "ObolSilverMining": "Silver_Obol_of_Moderate_Mining",
  "ObolSilverMoney": "Silver_Obol_of_Pocket_Change",
  "ObolSilverPop": "Silver_Obol_of_Pop_Pop",
  "ObolSilverTrapping": "Silver_Obol_of_Trapping",
  "ObolSilverWorship": "Silver_Obol_of_Worship"
}

const obolFamilyShapeMap = {
  0: 'Circle',
  1: 'Circle',
  2: 'Square',
  3: 'Circle',
  4: 'Circle',
  5: 'Circle',
  6: 'Hexagon',
  7: 'Sparkle',
  8: 'Hexagon',
  9: 'Circle',
  10: 'Square',
  11: 'Sparkle',
  12: 'Sparkle',
  13: 'Square',
  14: 'Circle',
  15: 'Hexagon',
  16: 'Sparkle',
  17: 'Hexagon',
  18: 'Circle',
  19: 'Circle',
  20: 'Circle',
  21: 'Square',
  22: 'Circle',
  23: 'Circle',
};

const obolCharacterShapeMap = {
  0: 'Square',
  1: 'Circle',
  2: 'Hexagon',
  3: 'Circle',
  4: 'Square',
  5: 'Circle',
  6: 'Circle',
  7: 'Circle',
  8: 'Circle',
  9: 'Square',
  10: 'Sparkle',
  11: 'Square',
  12: 'Circle',
  13: 'Circle',
  14: 'Circle',
  15: 'Circle',
  16: 'Square',
  17: 'Circle',
  18: 'Hexagon',
  19: 'Circle',
  20: 'Square',
};

const filteredLootyItems = {
  'EquipmentShirts4': true,
  'EquipmentShirts6': true,
  'EquipmentShirts8': true,
  'EquipmentShirts9': true,
  'EquipmentShoes2': true,
  'EquipmentShoes6': true,
  'EquipmentShoes8': true,
  'EquipmentShoes10': true,
  'EquipmentShoes13': true,
  'EquipmentShoes11': true,
  'EquipmentShoes12': true,
  'EquipmentShoes14': true,
  "EquipmentPendant1": true,
  "EquipmentPendant2": true,
  "EquipmentPendant3": true,
  "EquipmentPendant4": true,
  "EquipmentPendant5": true,
  "EquipmentPendant6": true,
  "EquipmentPendant7": true,
  "EquipmentPendant8": true,
  "EquipmentPendant13": true,
  "EquipmentPendant15": true,
  "EquipmentPendant18": true,
  "EquipmentRings1": true,
  "EquipmentRings4": true,
  "EquipmentRings5": true,
  "EquipmentRings8": true,
  "EquipmentRings9": true,
  "EquipmentRings10": true,
  "EquipmentRingsFishing1": true,
  "EquipmentRingsFishing2": true,
  "EquipmentRingsFishing3": true,
  "EquipmentHatsBeg1": true,
  "EquipmentHats10": true,
  "EquipmentHats23": true,
  "EquipmentHats24": true,
  "EquipmentHats27": true,
  "TestObj14": true,
  "TestObj15": true,
  "TestObj16": true,
  "EquipmentWeapons1": true,
  "EquipmentWeapons2": true,
  "EquipmentWands3": true,
  "EquipmentWands4": true,
  "TestObj2": true,
  "TestObj4": true,
  "TestObj5": true,
  "EquipmentPants7": true,
  "EquipmentPants8": true,
  "EquipmentPants9": true,
  "EquipmentPants11": true,
  "EquipmentPants12": true,
  "EquipmentPants13": true,
  "EquipmentPants14": true,
  'Blank': true,
  'LockedInvSpace': true,
  'FillerMaterial': true,
  'Fish5': true,
  'Fish6': true,
  'Fish7': true,
  'Fish8': true,
  'EquipmentSmithingTabs5': true,
  'EquipmentSmithingTabs6': true,
  'EquipmentSmithingTabs7': true,
  'EquipmentSmithingTabs8': true,
  'StampA29': true,
  'StampA30': true,
  'StampA31': true,
  'StampA32': true,
  'StampA33': true,
  'StampA34': true,
  'StampA35': true,
  'CraftMat11': true,
  'CraftMat12': true,
  'CraftMat13': true,
  'CraftMat14': true,
  'CraftMat15': true,
  'CraftMat16': true,
  'CraftMat17': true,
};

const stampsMap = {
  "combat": {
    "0": {
      "name": "Sword_Stamp",
      "rawName": "StampA1"
    },
    "1": {
      "name": "Heart_Stamp",
      "rawName": "StampA2"
    },
    "2": {
      "name": "Mana_Stamp",
      "rawName": "StampA3"
    },
    "3": {
      "name": "Tomahawk_Stamp",
      "rawName": "StampA4"
    },
    "4": {
      "name": "Target_Stamp",
      "rawName": "StampA5"
    },
    "5": {
      "name": "Shield_Stamp",
      "rawName": "StampA6"
    },
    "6": {
      "name": "Longsword_Stamp",
      "rawName": "StampA7"
    },
    "7": {
      "name": "Kapow_Stamp",
      "rawName": "StampA8"
    },
    "8": {
      "name": "Fist_Stamp",
      "rawName": "StampA9"
    },
    "9": {
      "name": "Battleaxe_Stamp",
      "rawName": "StampA10"
    },
    "10": {
      "name": "Agile_Stamp",
      "rawName": "StampA11"
    },
    "11": {
      "name": "Vitality_Stamp",
      "rawName": "StampA12"
    },
    "12": {
      "name": "Book_Stamp",
      "rawName": "StampA13"
    },
    "13": {
      "name": "Manamoar_Stamp",
      "rawName": "StampA14"
    },
    "14": {
      "name": "Clover_Stamp",
      "rawName": "StampA15"
    },
    "15": {
      "name": "Scimitar_Stamp",
      "rawName": "StampA16"
    },
    "16": {
      "name": "Bullseye_Stamp",
      "rawName": "StampA17"
    },
    "17": {
      "name": "Feather_Stamp",
      "rawName": "StampA18"
    },
    "18": {
      "name": "Polearm_Stamp",
      "rawName": "StampA19"
    },
    "19": {
      "name": "Violence_Stamp",
      "rawName": "StampA20"
    },
    "20": {
      "name": "Buckler_Stamp",
      "rawName": "StampA21"
    },
    "21": {
      "name": "FILLER",
      "rawName": "StampA22"
    },
    "22": {
      "name": "Sukka_Foo",
      "rawName": "StampA23"
    },
    "23": {
      "name": "Arcane_Stamp",
      "rawName": "StampA24"
    },
    "24": {
      "name": "FILLER",
      "rawName": "StampA25"
    },
    "25": {
      "name": "Steve_Sword",
      "rawName": "StampA26"
    },
    "26": {
      "name": "Blover_Stamp",
      "rawName": "StampA27"
    },
    "27": {
      "name": "Stat_Graph_Stamp",
      "rawName": "StampA28"
    },
    "28": {
      "name": "FILLER",
      "rawName": "StampA29"
    },
    "29": {
      "name": "FILLER",
      "rawName": "StampA30"
    },
    "30": {
      "name": "FILLER",
      "rawName": "StampA31"
    },
    "31": {
      "name": "FILLER",
      "rawName": "StampA32"
    },
    "32": {
      "name": "FILLER",
      "rawName": "StampA33"
    },
    "33": {
      "name": "FILLER",
      "rawName": "StampA34"
    },
    "34": {
      "name": "FILLER",
      "rawName": "StampA35"
    }
  },
  "skills": {
    "0": {
      "name": "Pickaxe_Stamp",
      "rawName": "StampB1"
    },
    "1": {
      "name": "Hatchet_Stamp",
      "rawName": "StampB2"
    },
    "2": {
      "name": "Anvil_Zoomer_Stamp",
      "rawName": "StampB3"
    },
    "3": {
      "name": "Lil' Mining_Baggy_Stamp",
      "rawName": "StampB4"
    },
    "4": {
      "name": "Twin_Ores_Stamp",
      "rawName": "StampB5"
    },
    "5": {
      "name": "Choppin' Bag_Stamp",
      "rawName": "StampB6"
    },
    "6": {
      "name": "Duplogs_Stamp",
      "rawName": "StampB7"
    },
    "7": {
      "name": "Matty_Bag_Stamp",
      "rawName": "StampB8"
    },
    "8": {
      "name": "Smart_Dirt_Stamp",
      "rawName": "StampB9"
    },
    "9": {
      "name": "Cool_Diggy_Tool_Stamp",
      "rawName": "StampB10"
    },
    "10": {
      "name": "High_IQ_Lumber_Stamp",
      "rawName": "StampB11"
    },
    "11": {
      "name": "Swag_Swingy_Tool_Stamp",
      "rawName": "StampB12"
    },
    "12": {
      "name": "Alch_Go_Brrr_Stamp",
      "rawName": "StampB13"
    },
    "13": {
      "name": "Brainstew_Stamps",
      "rawName": "StampB14"
    },
    "14": {
      "name": "Drippy_Drop_Stamp",
      "rawName": "StampB15"
    },
    "15": {
      "name": "Droplots_Stamp",
      "rawName": "StampB16"
    },
    "16": {
      "name": "Fishing_Rod_Stamp",
      "rawName": "StampB17"
    },
    "17": {
      "name": "Fishhead_Stamp",
      "rawName": "StampB18"
    },
    "18": {
      "name": "Catch_Net_Stamp",
      "rawName": "StampB19"
    },
    "19": {
      "name": "Fly_Intel_Stamp",
      "rawName": "StampB20"
    },
    "20": {
      "name": "Bag_o_Heads_Stamp",
      "rawName": "StampB21"
    },
    "21": {
      "name": "Holy_Mackerel_Stamp",
      "rawName": "StampB22"
    },
    "22": {
      "name": "Bugsack_Stamp",
      "rawName": "StampB23"
    },
    "23": {
      "name": "Buzz_Buzz_Stamp",
      "rawName": "StampB24"
    },
    "24": {
      "name": "Hidey_Box_Stamp",
      "rawName": "StampB25"
    },
    "25": {
      "name": "Purp_Froge_Stamp",
      "rawName": "StampB26"
    },
    "26": {
      "name": "Spikemouth_Stamp",
      "rawName": "StampB27"
    },
    "27": {
      "name": "Shiny_Crab_Stamp",
      "rawName": "StampB28"
    },
    "28": {
      "name": "Gear_Stamp",
      "rawName": "StampB29"
    },
    "29": {
      "name": "Sample_Stamp",
      "rawName": "StampB30"
    },
    "30": {
      "name": "Saw_Stamp",
      "rawName": "StampB31"
    },
    "31": {
      "name": "Amplesample_Stamp",
      "rawName": "StampB32"
    },
    "32": {
      "name": "SpoOoky_Stamp",
      "rawName": "StampB33"
    },
    "33": {
      "name": "Flowin_Stamp",
      "rawName": "StampB34"
    },
    "34": {
      "name": "Prayday_Stamp",
      "rawName": "StampB35"
    },
    "35": {
      "name": "Banked_Pts_Stamp",
      "rawName": "StampB36"
    }
  },
  "misc": {
    "0": {
      "name": "Questin_Stamp",
      "rawName": "StampC1"
    },
    "1": {
      "name": "Mason_Jar_Stamp",
      "rawName": "StampC2"
    },
    "2": {
      "name": "Crystallin",
      "rawName": "StampC3"
    },
    "3": {
      "name": "Blank",
      "rawName": "StampC4"
    },
    "4": {
      "name": "Apple_Stamp",
      "rawName": "StampC5"
    },
    "5": {
      "name": "Potion_Stamp",
      "rawName": "StampC6"
    },
    "6": {
      "name": "Golden_Apple_Stamp",
      "rawName": "StampC7"
    },
    "7": {
      "name": "Blank",
      "rawName": "StampC8"
    },
    "8": {
      "name": "Card_Stamp",
      "rawName": "StampC9"
    },
    "9": {
      "name": "Blank",
      "rawName": "StampC10"
    },
    "10": {
      "name": "Blank",
      "rawName": "StampC11"
    },
    "11": {
      "name": "Blank",
      "rawName": "StampC12"
    },
    "12": {
      "name": "Talent_I_Stamp",
      "rawName": "StampC13"
    },
    "13": {
      "name": "Talent_II_Stamp",
      "rawName": "StampC14"
    },
    "14": {
      "name": "Talent_III_Stamp",
      "rawName": "StampC15"
    },
    "15": {
      "name": "Talent_IV_Stamp",
      "rawName": "StampC16"
    },
    "16": {
      "name": "Talent_V_Stamp",
      "rawName": "StampC17"
    },
    "17": {
      "name": "Talent_S_Stamp",
      "rawName": "StampC18"
    },
    "18": {
      "name": "Multikill_Stamp",
      "rawName": "StampC19"
    },
    "19": {
      "name": "Biblio_Stamp",
      "rawName": "StampC20"
    }
  }
};

const maxCarryCap = {
  "Mining": {
    25: {
      name: 'Miniature_Mining_Pouch',
      rawName: 'MaxCapBagT2'
    },
    50: {
      name: 'Cramped_Mining_Pouch',
      rawName: 'MaxCapBag1'
    },
    100: {
      name: 'Small_Mining_Pouch',
      rawName: 'MaxCapBag2'
    },
    250: {
      name: 'Average_Mining_Pouch',
      rawName: 'MaxCapBag3'
    },
    500: {
      name: 'Sizable_Mining_Pouch',
      rawName: 'MaxCapBag4'
    },
    1000: {
      name: 'Big_Mining_Pouch',
      rawName: 'MaxCapBag5'
    },
    2000: {
      name: 'Large_Mining_Pouch',
      rawName: 'MaxCapBagMi6'
    }
  },
  "Chopping": {
    25: {
      name: 'Miniature_Choppin_Pouch',
      rawName: 'MaxCapBagT1'
    },
    50: {
      name: 'Cramped_Choppin_Pouch',
      rawName: 'MaxCapBag7'
    },
    100: {
      name: 'Small_Choppin_Pouch',
      rawName: 'MaxCapBag9'
    },
    250: {
      name: 'Average_Choppin_Pouch',
      rawName: 'MaxCapBagT3'
    },
    500: {
      name: 'Sizable_Choppin_Pouch',
      rawName: 'MaxCapBagT4'
    },
    1000: {
      name: 'Big_Choppin_Pouch',
      rawName: 'MaxCapBagT5'
    },
    2000: {
      name: 'Large_Choppin_Pouch',
      rawName: 'MaxCapBagT6'
    }
  },
  "Foods": {
    25: {
      name: 'Miniscule_Food_Pouch',
      rawName: 'MaxCapBag6'
    },
    50: {
      name: 'Cramped_Food_Pouch',
      rawName: 'MaxCapBag8'
    },
    100: {
      name: 'Small_Food_Pouch',
      rawName: 'MaxCapBag10'
    },
    250: {
      name: 'Average_Food_Pouch',
      rawName: 'MaxCapBagF3'
    },
    500: {
      name: 'Sizable_Food_Pouch',
      rawName: 'MaxCapBagF4'
    },
    1000: {
      name: 'Big_Food_Pouch',
      rawName: 'MaxCapBagF5'
    },
    2000: {
      name: 'Large_Food_Pouch',
      rawName: 'MaxCapBagF6'
    }
  },
  "bCraft": {
    25: {
      name: 'Mini_Materials_Pouch',
      rawName: 'MaxCapBagM1'
    },
    50: {
      name: 'Cramped_Material_Pouch',
      rawName: 'MaxCapBagM2'
    },
    100: {
      name: 'Small_Material_Pouch',
      rawName: 'MaxCapBagM3'
    },
    250: {
      name: 'Average_Material_Pouch',
      rawName: 'MaxCapBagM4'
    },
    500: {
      name: 'Sizable_Materials_Pouch',
      rawName: 'MaxCapBagM5'
    },
    1000: {
      name: 'Big_Materials_Pouch',
      rawName: 'MaxCapBagM6'
    },
    2000: {
      name: 'Large_Materials_Pouch',
      rawName: 'MaxCapBagM7'
    }
  },
  "Fishing": {
    25: {
      name: 'Miniature_Fish_Pouch',
      rawName: 'MaxCapBagFi0'
    },
    50: {
      name: 'Cramped_Fish_Pouch',
      rawName: 'MaxCapBagFi1'
    },
    100: {
      name: 'Small_Fish_Pouch',
      rawName: 'MaxCapBagFi2'
    },
    250: {
      name: 'Average_Fish_Pouch',
      rawName: 'MaxCapBagFi3'
    },
    500: {
      name: 'Sizable_Fish_Pouch',
      rawName: 'MaxCapBagFi4'
    },
    1000: {
      name: 'Big_Fish_Pouch',
      rawName: 'MaxCapBagFi5'
    },
    2000: {
      name: 'Large_Fish_Pouch',
      rawName: 'MaxCapBagFi6'
    }
  },
  "Bugs": {
    25: {
      name: 'Miniature_Bug_Pouch',
      rawName: 'MaxCapBagB0'
    },
    50: {
      name: 'Cramped_Bug_Pouch',
      rawName: 'MaxCapBagB1'
    },
    100: {
      name: 'Small_Bug_Pouch',
      rawName: 'MaxCapBagB2'
    },
    250: {
      name: 'Average_Bug_Pouch',
      rawName: 'MaxCapBagB3'
    },
    500: {
      name: 'Sizable_Bug_Pouch',
      rawName: 'MaxCapBagB4'
    },
    1000: {
      name: 'Big_Bug_Pouch',
      rawName: 'MaxCapBagB5'
    },
    2000: {
      name: 'Large_Bug_Pouch',
      rawName: 'MaxCapBagB6'
    }
  },
  "Critters": {
    50: {
      name: 'Cramped_Critter_Pouch',
      rawName: 'MaxCapBagTr0'
    },
    100: {
      name: 'Small_Critter_Pouch',
      rawName: 'MaxCapBagTr1'
    },
    250: {
      name: 'Average_Critter_Pouch',
      rawName: 'MaxCapBagTr2'
    },
    500: {
      name: 'Sizable_Critter_Pouch',
      rawName: 'MaxCapBagTr3'
    },
    1000: {
      name: 'Big_Critter_Pouch',
      rawName: 'MaxCapBagTr4'
    },
    2000: {
      name: 'Large_Critter_Pouch',
      rawName: 'MaxCapBagTr5'
    }
  },
  "Souls": {
    50: {
      name: 'Cramped_Soul_Pouch',
      rawName: 'MaxCapBagS0'
    },
    100: {
      name: 'Small_Soul_Pouch',
      rawName: 'MaxCapBagS1'
    },
    250: {
      name: 'Average_Soul_Pouch',
      rawName: 'MaxCapBagS2'
    },
    500: {
      name: 'Sizable_Soul_Pouch',
      rawName: 'MaxCapBagS3'
    },
    1000: {
      name: 'Big_Soul_Pouch',
      rawName: 'MaxCapBagS4'
    },
    2000: {
      name: 'Large_Soul_Pouch',
      rawName: 'MaxCapBagS5'
    }
  }
};

const statuesMap = {
  0: { name: "Power_Statue", rawName: "Statue1" },
  1: { name: "Speed_Statue", rawName: "Statue2" },
  2: { name: "Mining_Statue", rawName: "Statue3" },
  3: { name: "Feasty_Statue", rawName: "Statue4" },
  4: { name: "Health_Statue", rawName: "Statue5" },
  5: { name: "Kachow_Statue", rawName: "Statue6" },
  6: { name: "Lumberbob_Statue", rawName: "Statue7" },
  7: { name: "Thicc_Skin_Statue", rawName: "Statue8" },
  8: { name: "Oceanman_Statue", rawName: "Statue9" },
  9: { name: "Ol_Reliable_Statue", rawName: "Statue10" },
  10: { name: "Exp_Book_Statue", rawName: "Statue11" },
  11: { name: "Anvil_Statue", rawName: "Statue12" },
  12: { name: "Cauldron_Statue", rawName: "Statue13" },
  13: { name: "Beholder_Statue", rawName: "Statue14" },
  14: { name: "Bullseye_Statue", rawName: "Statue15" },
  15: { name: "Box_Statue", rawName: "Statue16" },
  16: { name: "Twosoul_Statue", rawName: "Statue17" },
  17: { name: "EhExPee_Statue", rawName: "Statue18" }
}

// module.exports = {
//   starSignMap,
//   classMap,
//   mapsMap,
//   itemMap,
//   bubblesMap,
//   cardSetMap,
//   cardEquipMap,
//   cardLevelMap,
//   skillIndexMap,
//   guildBonusesMap,
//   obolMap,
//   obolFamilyShapeMap,
//   obolCharacterShapeMap,
//   filteredLootyItems,
//   anvilProductionItems,
//   stampsMap,
//   maxCarryCap,
//   statuesMap
// };


